import { type BuiltinPlugin, type PluginRegistry } from './types.js';
import { createPluginRegistry } from './registry.js';

export const BUILTIN_PLUGINS: BuiltinPlugin[] = [
  {
    name: 'eslint',
    configPatterns: [
      'eslint.config.*',
      '.eslintrc',
      '.eslintrc.js',
      '.eslintrc.cjs',
      '.eslintrc.mjs',
      '.eslintrc.json',
      '.eslintrc.yaml',
      '.eslintrc.yml',
      '.eslintignore',
    ],
    toolingPackages: ['eslint', '@eslint/', 'eslint-plugin-', 'eslint-config-'],
    typesPackages: [],
  },
  {
    name: 'prettier',
    configPatterns: [
      '.prettierrc',
      '.prettierrc.js',
      '.prettierrc.cjs',
      '.prettierrc.mjs',
      '.prettierrc.json',
      '.prettierrc.json5',
      '.prettierrc.yaml',
      '.prettierrc.yml',
      '.prettierrc.toml',
      'prettier.config.js',
      'prettier.config.cjs',
      'prettier.config.mjs',
      '.prettierignore',
    ],
    toolingPackages: ['prettier', 'prettier-plugin-'],
  },
  {
    name: '@biomejs/biome',
    configPatterns: ['biome.json', 'biome.jsonc'],
    toolingPackages: ['@biomejs/biome'],
  },
  {
    name: 'stylelint',
    configPatterns: [
      '.stylelintrc',
      '.stylelintrc.js',
      '.stylelintrc.cjs',
      '.stylelintrc.mjs',
      '.stylelintrc.json',
      '.stylelintrc.yaml',
      '.stylelintrc.yml',
      'stylelint.config.js',
      'stylelint.config.cjs',
      'stylelint.config.mjs',
    ],
    toolingPackages: ['stylelint', 'stylelint-config-', 'stylelint-plugin-'],
  },
  {
    name: 'oxlint',
    configPatterns: ['oxlint.json', '.oxlintrc', '.oxlintrc.json'],
    toolingPackages: ['oxlint'],
  },
  {
    name: 'jest',
    configPatterns: [
      'jest.config.js',
      'jest.config.cjs',
      'jest.config.mjs',
      'jest.config.ts',
      'jest.config.cts',
      'jest.config.mts',
      'jest.config.json',
      'jest.setup.js',
      'jest.setup.ts',
      'jest.setup.cjs',
      'jest.setup.mjs',
    ],
    toolingPackages: ['jest', '@jest/', 'jest-'],
    entryPatterns: ['**/__tests__/**/*.{js,ts,jsx,tsx}', '**/*.{spec,test}.{js,ts,jsx,tsx}'],
    typesPackages: ['jest'],
  },
  {
    name: 'vitest',
    configPatterns: [
      'vitest.config.js',
      'vitest.config.cjs',
      'vitest.config.mjs',
      'vitest.config.ts',
      'vitest.config.cts',
      'vitest.config.mts',
      'vitest.setup.js',
      'vitest.setup.ts',
    ],
    toolingPackages: ['vitest', '@vitest/'],
    entryPatterns: ['**/*.{spec,test}.{js,ts,jsx,tsx}'],
    typesPackages: ['vitest'],
  },
  {
    name: '@playwright/test',
    configPatterns: [
      'playwright.config.js',
      'playwright.config.ts',
      'playwright.config.mjs',
      'playwright.config.cjs',
    ],
    toolingPackages: ['@playwright/test', 'playwright'],
    typesPackages: ['playwright'],
  },
  {
    name: 'cypress',
    configPatterns: [
      'cypress.config.js',
      'cypress.config.ts',
      'cypress.config.cjs',
      'cypress.config.mjs',
      'cypress/**',
    ],
    toolingPackages: ['cypress'],
    entryPatterns: ['cypress/e2e/**/*.{js,ts,jsx,tsx}', 'cypress/integration/**/*.{js,ts,jsx,tsx}'],
    typesPackages: ['cypress'],
  },
  {
    name: 'mocha',
    configPatterns: [
      '.mocharc.js',
      '.mocharc.cjs',
      '.mocharc.mjs',
      '.mocharc.json',
      '.mocharc.jsonc',
      '.mocharc.yaml',
      '.mocharc.yml',
    ],
    toolingPackages: ['mocha', '@types/mocha'],
    typesPackages: ['mocha'],
  },
  {
    name: 'vite',
    configPatterns: [
      'vite.config.js',
      'vite.config.ts',
      'vite.config.mjs',
      'vite.config.cjs',
      'vite.config.mts',
      'vite.config.cts',
    ],
    toolingPackages: ['vite', '@vitejs/'],
  },
  {
    name: 'webpack',
    configPatterns: [
      'webpack.config.js',
      'webpack.config.ts',
      'webpack.config.mjs',
      'webpack.config.cjs',
      'webpack.config.babel.js',
    ],
    toolingPackages: ['webpack', 'webpack-cli', 'webpack-dev-server', 'webpack-merge', 'webpack-plugin-'],
  },
  {
    name: 'rollup',
    configPatterns: [
      'rollup.config.js',
      'rollup.config.ts',
      'rollup.config.mjs',
      'rollup.config.cjs',
    ],
    toolingPackages: ['rollup', '@rollup/'],
  },
  {
    name: 'esbuild',
    configPatterns: [
      'esbuild.config.js',
      'esbuild.config.ts',
      'esbuild.config.mjs',
      'esbuild.config.cjs',
      'build.js',
      'build.ts',
    ],
    toolingPackages: ['esbuild'],
  },
  {
    name: 'tsup',
    configPatterns: [
      'tsup.config.js',
      'tsup.config.ts',
      'tsup.config.mjs',
      'tsup.config.cjs',
      'tsup.config.json',
    ],
    toolingPackages: ['tsup'],
  },
  {
    name: 'parcel',
    configPatterns: ['.parcelrc', '.parcelrc.json'],
    toolingPackages: ['parcel', '@parcel/'],
  },
  {
    name: '@babel/core',
    configPatterns: [
      'babel.config.js',
      'babel.config.cjs',
      'babel.config.mjs',
      'babel.config.json',
      'babel.config.ts',
      '.babelrc',
      '.babelrc.js',
      '.babelrc.cjs',
      '.babelrc.mjs',
      '.babelrc.json',
    ],
    toolingPackages: ['@babel/', 'babel-plugin-', 'babel-preset-'],
  },
  {
    name: '@swc/core',
    configPatterns: [
      '.swcrc',
      'swc.config.js',
      'swc.config.ts',
      'swc.config.mjs',
      'swc.config.cjs',
    ],
    toolingPackages: ['@swc/', 'swc-'],
  },
  {
    name: 'nx',
    configPatterns: ['nx.json', 'project.json', '.nxignore'],
    toolingPackages: ['nx', '@nx/'],
  },
  {
    name: 'turbo',
    configPatterns: ['turbo.json'],
    toolingPackages: ['turbo', 'turborepo'],
  },
  {
    name: 'lerna',
    configPatterns: ['lerna.json'],
    toolingPackages: ['lerna'],
  },
  {
    name: '@changesets/cli',
    configPatterns: ['.changeset/config.json', '.changeset/*.md'],
    toolingPackages: ['@changesets/'],
  },
  {
    name: 'husky',
    configPatterns: [
      '.husky/**',
      '.huskyrc',
      '.huskyrc.js',
      '.huskyrc.json',
      '.huskyrc.yaml',
      '.huskyrc.yml',
    ],
    toolingPackages: ['husky'],
  },
  {
    name: 'lint-staged',
    configPatterns: [
      '.lintstagedrc',
      '.lintstagedrc.js',
      '.lintstagedrc.cjs',
      '.lintstagedrc.mjs',
      '.lintstagedrc.json',
      '.lintstagedrc.yaml',
      '.lintstagedrc.yml',
      'lint-staged.config.js',
      'lint-staged.config.cjs',
      'lint-staged.config.mjs',
      'lint-staged.config.ts',
    ],
    toolingPackages: ['lint-staged'],
  },
  {
    name: '@commitlint/cli',
    configPatterns: [
      'commitlint.config.js',
      'commitlint.config.cjs',
      'commitlint.config.mjs',
      'commitlint.config.ts',
      '.commitlintrc',
      '.commitlintrc.js',
      '.commitlintrc.cjs',
      '.commitlintrc.mjs',
      '.commitlintrc.json',
      '.commitlintrc.yaml',
      '.commitlintrc.yml',
    ],
    toolingPackages: ['@commitlint/'],
  },
  {
    name: '@storybook/core',
    configPatterns: [
      '.storybook/**',
      'storybook.config.js',
      'storybook.config.ts',
    ],
    toolingPackages: ['@storybook/', 'storybook'],
    entryPatterns: ['**/*.stories.{js,ts,jsx,tsx,mdx}'],
  },
  {
    name: 'typescript',
    configPatterns: [
      'tsconfig.json',
      'tsconfig.*.json',
      'tsconfig.*.jsonc',
    ],
    toolingPackages: ['typescript', 'ts-node', 'ts-jest', 'tsx'],
  },
  {
    name: 'docker',
    configPatterns: [
      'Dockerfile',
      'Dockerfile.*',
      'docker-compose.yml',
      'docker-compose.yaml',
      'docker-compose.*.yml',
      'docker-compose.*.yaml',
      '.dockerignore',
    ],
    toolingPackages: [],
  },
  {
    name: 'vercel',
    configPatterns: ['vercel.json', '.vercelignore'],
    toolingPackages: ['vercel', '@vercel/'],
  },
  {
    name: 'netlify',
    configPatterns: [
      'netlify.toml',
      '_redirects',
      '_headers',
    ],
    toolingPackages: ['netlify-cli', 'netlify-lambda'],
  },
];

export const DEFAULT_PLUGIN_REGISTRY: PluginRegistry = createPluginRegistry(BUILTIN_PLUGINS);

export const ALWAYS_DEV_TOOLING: string[] = [
  '@types/',
  'eslint',
  'prettier',
  'jest',
  'vitest',
  'mocha',
  'chai',
  'sinon',
  'jasmine',
  '@jest/',
  '@vitest/',
  'typescript',
  'ts-node',
  'tsx',
  'ts-jest',
  'webpack',
  'webpack-cli',
  'webpack-dev-server',
  'rollup',
  'vite',
  '@vitejs/',
  'esbuild',
  'tsup',
  'parcel',
  '@parcel/',
  '@babel/',
  'babel-plugin-',
  'babel-preset-',
  '@swc/',
  'eslint-plugin-',
  'eslint-config-',
  '@eslint/',
  'stylelint',
  'stylelint-config-',
  'stylelint-plugin-',
  'oxlint',
  '@biomejs/biome',
  'prettier-plugin-',
  'husky',
  'lint-staged',
  '@commitlint/',
  'commitizen',
  '@changesets/',
  'lerna',
  'turbo',
  'nx',
  '@nx/',
  '@storybook/',
  'storybook',
  '@playwright/test',
  'playwright',
  'cypress',
  'nodemon',
  'concurrently',
  'cross-env',
  'rimraf',
  'del-cli',
  'npm-run-all',
  'wait-on',
  'dotenv-cli',
  'standard-version',
  'semantic-release',
  '@semantic-release/',
  'release-it',
  'auto',
  'size-limit',
  'bundlesize',
];
