export * from './types.js';
export * from './storage/db.js';
export * from './storage/node-store.js';
export * from './storage/edge-store.js';
export * from './storage/fts-store.js';
export * from './storage/embedding-store.js';
export { findUnlinkedReferences, type UnlinkedReference } from './storage/unlinked-refs.js';
export { parseCodeowners, resolveOwner, annotateOwnership, groupByOwner, type CodeownersEntry, type OwnershipResult } from './graph/codeowners.js';
export { addSuppression, listSuppressions, removeSuppression, isSuppressed, findStaleSuppressions, type Suppression, type StaleSuppression } from './storage/suppressions.js';
export * from './pipeline/runner.js';
export * from './pipeline/types.js';
export * from './pipeline/orchestrator.js';
export { classifyReachability, getNodesByReachabilityRole, type ReachabilityRole } from './pipeline/phases/reachability.js';
export { exportSarif, type SarifDocument, type SarifResult, type SarifRule } from './export/sarif.js';
export { detectBoundaryViolations, loadMonographConfig, classifyZone, type BoundaryViolation, type ZoneConfig, type MonographConfig } from './pipeline/phases/boundary.js';
export * from './graph/loader.js';
export * from './graph/analyzer.js';
export { computeCouplingProfile, computeGraphStats, type CouplingProfile, type RiskProfile, type GraphStatsSummary } from './graph/stats.js';
export { computeMaintainabilityIndex, type MaintainabilityResult, type MaintainabilityReport } from './graph/maintainability.js';
export { hashFileContent, isFileCached, updateFileCache, getFileCacheStats, clearFileCache, type FileCacheEntry } from './storage/file-cache.js';
export * from './graph/diff.js';
export { explainRule, listRules, getRulesByFinding, CHECK_RULES, type RuleDef } from './graph/explain.js';
export { computeDependencyClosure, type DepClosureResult, type DepClosureReport } from './graph/dependency-closure.js';
export { computeHotspots, type HotspotResult } from './graph/hotspots.js';
export { detectMirroredDirs, type MirroredDirPair, type MirroredDirsReport } from './graph/mirrored-dirs.js';
export { crossReferenceDuplicatesAndDeadCode, type CrossReferenceFinding, type CrossReferenceReport } from './graph/cross-reference.js';
export { computeHealthScore, letterGrade, type HealthScoreResult, type HealthScorePenalties } from './graph/health-score.js';
export { computeAuthorAnalytics, type AuthorStats, type AuthorAnalyticsReport, type ChurnTrend } from './graph/author-analytics.js';
export { computeRiskProfile, type SizeBin, type RiskProfileReport } from './graph/risk-profile.js';
export * from './watch/watcher.js';
export * from './export/json.js';
export * from './export/html.js';
export * from './export/cypher.js';
export * from './export/graphml.js';
export * from './export/svg.js';
export { saveBaseline, loadBaseline, compareWithBaseline, extractFindingsFromDb, defaultBaselinePath, computeTrend, type BaselineFinding, type BaselineData, type ComparedFinding, type BaselineVitals, type TrendReport, type TrendMetric, type TrendDirection } from './graph/baseline.js';
export { checkRegression, Tolerance, type RegressionOutcome, type RegressionMetric } from './graph/regression.js';
export { detectClones, type ClonePair, type CloneDetectionResult } from './graph/clone-detector.js';
export { createShingleFilter, type ShingleFilter } from './graph/shingle-filter.js';
export { computeComplexity, computeCrapScore, type FunctionComplexity, type ComplexityReport } from './graph/complexity.js';
export { detectCycles, type DependencyCycle, type CycleDetectionResult } from './analysis/cycles.js';
export { computeCoverageGaps, type UntestedFile, type UntestedExport, type CoverageGapsResult } from './analysis/coverage-gaps.js';
export { detectDuplicateExports, type DuplicateExportGroup, type DuplicateExportsResult } from './analysis/duplicate-exports.js';
export { computeRefactoringTargets, type RefactoringTarget, type RefactoringTargetsResult, type RecommendationCategory, type EffortEstimate, type TargetConfidence, computeTargetPriority, tryMatchPriorityRules, normalizeMetric, PRIORITY_RULE_WEIGHTS, type ContributingFactor, type EvidenceFunction, type TargetEvidence, type PriorityRule } from './analysis/targets.js';
export { runAudit, type AuditSummary, type AuditVerdict, type AuditGate, type AuditAttribution } from './audit.js';
export { detectPrivateTypeLeaks, type PrivateTypeLeak, type PrivateTypeLeaksResult } from './analysis/private-type-leaks.js';
export { fixUnusedExports, type ExportFix, type FixResult } from './fix/exports.js';
export { fixUnusedDeps, type DepFix, type DepFixResult } from './fix/deps.js';
export { classifyDependencies, type PackageDepClassification, type DepClassificationResult } from './analysis/dep-classification.js';
export { generateBadge, gradeToColor, type BadgeOptions } from './export/badge.js';
export { exportCodeClimate, type CodeClimateIssue } from './export/codeclimate.js';
export { exportCompact } from './export/compact.js';
export { exportMarkdown, type MarkdownReportOptions } from './export/markdown.js';
export { analyzeRuntimeCoverage, type RuntimeClassification, type FunctionCoverageEntry, type RuntimeCoverageReport, type V8Coverage } from './coverage/runtime.js';
export { generateCiTemplate, type CiProvider, type CiTemplateOptions, type CiTemplate } from './ci-template.js';
export { migrateFromKnip, type KnipMigrationResult, type MigrationWarning } from './migrate/knip.js';
export { migrateFromJscpd, type JscpdMigrationResult } from './migrate/jscpd.js';
export { buildDiagnosticsFromDb, startLspServer, type LspDiagnostic } from './lsp/server.js';
// ── Round 5: Fallow feature ports ─────────────────────────────────────────────
export { buildSnapshot, saveSnapshot, loadSnapshots, latestSnapshot, SNAPSHOT_SCHEMA_VERSION, type VitalSignsSnapshot } from './health/vital-signs-snapshot.js';
export { computeTrend, trendArrow, STABLE_BAND, type HealthTrend, type TrendMetric, type TrendCount, type TrendDirection } from './health/trends.js';
export { computeHealthScore, letterGradeFromScore, HOTSPOT_SCORE_THRESHOLD, MI_DENSITY_MIN_LINES, type HealthScore, type HealthScorePenalties, type VitalSignsInput, type HealthGrade } from './health/health-score.js';
export { computeSizeRiskProfile, computeInterfacingRiskProfile, computeCouplingConcentration, type RiskProfile } from './health/risk-profile.js';
export { detectLargeFunctions, shouldReportLargeFunctions, LARGE_FUNCTION_LOC_THRESHOLD, LARGE_FUNCTION_REPORT_THRESHOLD_PCT, type LargeFunctionEntry } from './health/large-functions.js';
export { formatPerformanceTable, startTimer, type HealthTimings, type HealthPipelineTimings, ZERO_HEALTH_PIPELINE_TIMINGS, formatHealthPipelineTimings, sumHealthPipelineTimings } from './health/timings.js';
export { computeOwnershipMetrics, computeBusFactor, detectDrift, normalizeEmail, DRIFT_MIN_FILE_AGE_DAYS, DRIFT_MAX_ORIGINAL_SHARE, type EmailMode, type ContributorEntry, type OwnershipMetrics, type ContributorIdentifierFormat, normalizeContributorId } from './health/ownership.js';
export { computeHotspots, isTestPath, type HotspotInput, type HotspotEntry, type HotspotSummary } from './health/hotspots.js';
export { classifyRuntimeCoverageHealth, type RuntimeCoverageVerdict, type RuntimeCoverageRiskBand, type RuntimeCoverageAction, type RuntimeCoverageReportVerdict } from './health/runtime-coverage.js';
export { groupFilesByKey, type HealthGrouping, type HealthGroup } from './health/grouping.js';
export { buildAnalysisCountsSnapshot, countsFor, aggregateCounts, type AnalysisCountsSnapshot, type FileScoreOutput } from './health/analysis-counts-snapshot.js';
export { analyzeChurn, parseSince, computeRecencyWeight, type ChurnTrend, type SinceDuration, type FileChurn, type ChurnResult, type AuthorContribution } from './analysis/churn.js';
export { traceExport, traceFile, traceDependency, type ExportTrace, type FileTrace, type DependencyTrace, type CloneTrace, type TraceReason, type ReferenceLocation } from './analysis/trace.js';
export { getChangedFiles, validateGitRef, filterResultsByChangedFiles, ChangedFilesError } from './analysis/changed-files.js';
export { resolveAnalyses, runCombined, type AnalysisKind, type CombinedOptions, type CombinedResult } from './analysis/combined.js';
export { listBoundaries, listEntryPoints, formatBoundaryTable, type BoundaryRule, type PluginInfo, type ListOptions } from './analysis/list.js';
export { createSuppressionContext, markConsumed, findStale, NON_CORE_KINDS, type SuppressionKind, type Suppression, type StaleSuppression, type SuppressionContext } from './analysis/suppressions.js';
export { applyRules, resolveRulesForFile, type RuleSet, type RuleOverride, type IssueSeverity, type RuleWithSeverity, hasErrorSeverityIssues, promoteWarnsToErrors, demoteErrorsToWarns } from './analysis/rule-overrides.js';
export { filterToWorkspaces, createSubsetFilter, isInSubset, type SubsetFilter, type WorkspaceFilterPattern, parseWorkspaceFilterPattern, matchWorkspacePattern, resolveWorkspaceFilters, formatAvailableWorkspaces, workspacesContainingAny } from './analysis/workspace-filter.js';
export { buildHealthBaseline, filterNewHealthFindings, type HealthBaselineData, type HealthFileCounts, type HealthFinding } from './analysis/health-baseline.js';
export { parseTolerance, toleranceExceeded, saveBaselineToConfig, type Tolerance } from './analysis/regression-config.js';
export { fixEnumMembers, removeEnumMember, findEnumDeclarationRange, declaresExportedEnum, type EnumMemberFix, type EnumMemberFixResult } from './fix/enum-members.js';
export { parseCodeownersWithSections, matchOwners, parseSectionHeader, ownerCountOf, sectionOf, sectionAndOwnersOf, hasSections, CODEOWNERS_PROBE_PATHS, UNOWNED_LABEL, NO_SECTION_LABEL, type SectionHeader, type CodeownersEntry } from './graph/codeowners-gitlab.js';
export { buildCodeLenses, type MonographCodeLens, type ExportUsage } from './lsp/code-lens.js';
export { buildHover, type MonographHover, type UnusedExportInfo, type DuplicationInfo } from './lsp/hover.js';
export { buildDuplicateExportDiagnostics, buildStaleSuppressionDiagnostics, type MonographDiagnostic, type RelatedInformation, type DuplicateExportGroup } from './lsp/diagnostics.js';
// ── Round 6: Fallow feature ports ─────────────────────────────────────────────
export { analyzeFeatureFlags, crossReferenceWithDeadCode, summarizeFlags, DEFAULT_FLAGS_CONFIG, type FlagKind, type FlagConfidence, type FeatureFlag, type FlagsConfig, type FlagsSummary } from './analysis/feature-flags.js';
export { KNOWN_SDK_PATTERNS, detectSdkFromPackageJson, type SdkPattern } from './analysis/feature-flags-config.js';
export { getChangedWorkspaces, resolveChangedWorkspaceRoots, type WorkspacePackage } from './analysis/changed-workspaces.js';
export { groupIntoFamilies, cloneFamilySummary, MODULE_EXTRACTION_THRESHOLD_LINES, type RefactoringKind, type RefactoringSuggestion, type CloneInstance, type CloneGroup, type CloneFamily } from './graph/clone-families.js';
export { computeDuplicationStats, formatDuplicationStats, type DuplicationStats, type CloneGroupInput } from './graph/duplication-stats.js';
export { buildRemoveExportActions, buildSuppressActions, type LspTextEdit, type LspWorkspaceEdit, type CodeAction, type UnusedExportLocation, type ExportKeywordVariant, buildDeleteFileActions, type DeleteFileAction } from './lsp/code-actions.js';
export { buildUnusedSymbolDiagnostics, buildCircularDepDiagnostics, buildBoundaryViolationDiagnostics, buildComplexityDiagnostics, type UnusedSymbolLocation, type CircularDepLocation, type BoundaryViolationLocation, type ComplexityIssueLocation } from './lsp/diagnostics-ext.js';
export { validateConfig, type ValidationError, type ValidationResult } from './config/validate.js';
export { generateConfigSchema, schemaToJson, type JSONSchemaProperty, type JSONSchema } from './config/schema-gen.js';
export { getEffortProfile, parseEffort, type AnalysisEffort, type EffortProfile } from './pipeline/effort.js';
export { ProgressReporter, consoleProgressReporter, type ProgressPhase, type ProgressEvent, type ProgressCallback } from './pipeline/progress.js';
export { evaluateQualityGate, formatQualityGateResult, type QualityGateConfig, type QualityGateStatus, type QualityGateResult } from './health/quality-gate.js';
// ── Round 7: Fallow feature ports ─────────────────────────────────────────────
export { fetchRuntimeContext, buildCloudRequestUrl, isCloudError, type CloudRequest, type CloudRuntimeContext, type CloudRuntimeSummary, type CloudRuntimeFunction, type CloudRuntimeBlastRadiusEntry, type CloudRuntimeImportanceEntry, type CloudRuntimeRiskBand, type CloudTrackingState, type CloudRuntimeWarning, type CloudError, type CloudErrorKind } from './coverage/cloud-client.js';
export { uploadInventory, extractFunctionInventory, normalizePathPrefix, parseGitRemoteToProjectId, INVENTORY_MAX_FUNCTIONS, type UploadInventoryArgs, type InventoryFunction, type UploadInventoryResult } from './coverage/upload-inventory.js';
export { uploadSourceMaps, collectSourceMaps, applyStripPath, type UploadSourceMapsArgs, type SourceMapFile, type UploadSourceMapsResult } from './coverage/upload-source-maps.js';
export { activateTrial, refreshLicense, getFreeLicenseStatus, parseLicenseJwt, licenseStatusFromPayload, LicenseError, type LicenseTier, type LicenseStatus, type LicenseFeatures, type ActivateOptions, type LicenseJwtPayload } from './license/manager.js';
export { validateAnalysisOptions, isProgrammaticError, makeProgrammaticError, programmaticErrorToJson, type AnalysisOptions, type DeadCodeFilters, type DeadCodeOptions, type DuplicationOptions, type DuplicationMode, type ComplexityOptions, type ComplexitySort, type OwnershipEmailMode, type TargetEffort, type ProgrammaticError, type ProgrammaticRunOptions, detectDeadCodeProgrammatic, detectCircularDependenciesProgrammatic, detectBoundaryViolationsProgrammatic, detectDuplicationProgrammatic, computeComplexityProgrammatic, computeHealthProgrammatic } from './api/programmatic.js';
export { createRegressionBaseline, checkCountsDeltas, totalCheckCounts, ZERO_CHECK_COUNTS, REGRESSION_SCHEMA_VERSION, type RegressionBaseline, type CheckCounts, type DupesCounts, type CountDelta, type CheckCountsKey } from './regression/counts.js';
export { regressionOutcomeToJson, printRegressionOutcome, makePassOutcome, makeExceededOutcome, makeSkippedOutcome, type RegressionOutcome, type RegressionOutcomePass, type RegressionOutcomeExceeded, type RegressionOutcomeSkipped, type RegressionOutcomeKind } from './regression/outcome.js';
export { narrowNamespaceReferences, narrowCssModuleReferences, extractMemberAccesses, extractDestructuredMembers, isWholeObjectUse, type ReferenceKind, type NamespaceAccess, type NarrowingResult } from './graph/narrowing.js';
export { parseDynamicImports, resolveSingleDynamicImport, templateToGlob, matchGlob, type DynamicImportPattern, type DynamicImportInfo, type ResolvedDynamicImport } from './graph/resolve/dynamic-imports.js';
export { createPackageResolver, resolveDirectoryGroup, groupItemsByFile, largestOwner, attributeCloneGroup, type GroupByMode, type GroupEntry, type AttributedInstance, type AttributedCloneGroup, type PackageResolver } from './report/grouping.js';
export { createVitalSigns, formatVitalSignsSummary, VITAL_SIGNS_SCHEMA_VERSION, type VitalSigns, type VitalSignsCounts, type SizeBinProfile, type InterfacingProfile, type CoverageModel } from './health/vital-signs.js';
export { computeTargetThresholds, labelForCategory, compactLabelForCategory, RECOMMENDATION_CATEGORIES, type ExtendedRecommendationCategory, type CategoryMeta, type TargetThresholds, type MetricSample } from './health/target-thresholds.js';
export { isValidEmailMode, isValidAuditGate, type AnalyzeParams, type HealthParams, type CheckRuntimeCoverageParams, type AuditParams, type FindDupesParams, type TraceExportParams, type TraceFileParams, type TraceDependencyParams, type TraceCloneParams, type ProjectInfoParams, type FeatureFlagsParams, type ListBoundariesParams, type EmailModeParam, type AuditGate, type CheckChangedMcpParams, type FixMcpParams, type ExplainMcpParams, isValidFixMode } from './mcp/params.js';
export { resolveProductionMode, resolveAllProductionModes, buildBaselineAuditMeta, productionModeLabel, DEFAULT_PRODUCTION_MODE, type ProductionOverride, type ProductionModeConfig, type BaselineAuditMeta } from './api/production-override.js';
// ── Round 8: Fallow feature ports ─────────────────────────────────────────────
export { applyIssueFilters, activateExplicitOptIns, anyFiltersActive, parseIssueFilters, ALL_FILTERS_ON, ALL_FILTERS_OFF, type IssueFilters, type IssueFilterKey } from './analysis/issue-filters.js';
export { augmentExternalStylePackageUsage, isTrackableExternalStylePath, packageNameFromPath, scanStyleImports, type ExternalStyleImport, type ExternalStyleScanResult } from './graph/external-style-usage.js';
export { detectProject, detectFramework, detectTestRunner, detectPackageManager, buildJsonConfig, buildTomlConfig, type DetectedFramework, type DetectedTestRunner, type DetectedPackageManager, type DetectedMonorepoTool, type ProjectInfo } from './init/project-detection.js';
export { detectHooksManager, validateBranchName, renderedHookScript, mergeHookContent, removeHookBlock, GIT_HOOK_INSTALL_RESULT_NONE, type GitHooksManager, type GitHooksInstallOptions, type GitHooksInstallResult } from './init/git-hooks.js';
export { buildAgentsMdBlock, mergeAgentsMdBlock, removeAgentsMdBlock, buildClaudeCodeHookEntry, mergeClaudeCodeSettings, AGENTS_BLOCK_START, AGENTS_BLOCK_END, MONOGRAPH_GATE_SCRIPT, DEFAULT_SETUP_RESULT, type AgentHooksTarget, type SetupHooksOptions, type SetupHooksResult } from './init/agent-hooks.js';
export { computeDistributionThresholds, formatDistributionThresholds, THRESHOLD_FLOORS, type DistributionThresholds, type FileTopologyScore } from './health/distribution-thresholds.js';
export { computeAnalysisCounts, deadCodePct, unusedDepsPct, formatAnalysisCounts, ZERO_ANALYSIS_COUNTS, type AnalysisCounts, type AnalysisResultsInput } from './health/analysis-counts.js';
export { createHealthReport, createHealthReportSummary, formatHealthReportSummary, healthReportToJson, type HealthReport, type HealthReportSummary } from './health/health-report.js';
// ── Round 9: Fallow feature ports ─────────────────────────────────────────────
export { classifyFindingSeverity, summarizeFindings, coverageTierFromPct, DEFAULT_CYCLOMATIC_HIGH, DEFAULT_CYCLOMATIC_CRITICAL, DEFAULT_COGNITIVE_HIGH, DEFAULT_COGNITIVE_CRITICAL, DEFAULT_CRAP_HIGH, DEFAULT_CRAP_CRITICAL, COGNITIVE_EXTRACTION_THRESHOLD, type FindingSeverity, type ExceededThreshold, type CoverageTier, type HealthFinding, type HealthSummary, type FileHealthScore } from './health/complexity-findings.js';
export { createRuntimeCoverageReport, buildRuntimeCoverageSummary, type RuntimeCoverageConfidence, type RuntimeCoverageWatermark, type RuntimeCoverageDataSource, type RuntimeCoverageHotPath, type RuntimeCoverageBlastRadiusEntry, type RuntimeCoverageImportanceEntry, type RuntimeCoverageEvidence, type RuntimeCoverageCaptureQuality, type RuntimeCoverageMessage, type RuntimeCoverageFinding, type RuntimeCoverageSummary, type RuntimeCoverageReport } from './health/runtime-coverage-report.js';
export { buildDuplicationGrouping, defaultOwnerResolver, formatDuplicationGrouping, type DuplicationGroupEntry, type DuplicationGrouping, type OwnerResolver } from './report/duplication-grouping.js';
export { buildGroupedHealthJson, buildGroupedDuplicationJson, buildBaselineDeltasJson, DEFAULT_HEALTH_ACTION_OPTIONS, type HealthActionOptions, type GroupedHealthResult, type GroupedDuplicationResult, type BaselineDelta } from './report/json-builders.js';
export { saveRegressionBaseline, loadRegressionBaseline, compareWithRegressionBaseline, DEFAULT_REGRESSION_BASELINE_PATH, REGRESSION_BASELINE_VERSION, type RegressionBaselineFile, type SaveRegressionTarget, type RegressionBaselineOpts, type RegressionCompareResult } from './regression/baseline.js';
export { buildAnalyzeArgs, buildHealthArgs, buildAuditArgs, buildFindDupesArgs, buildTraceExportArgs, buildTraceFileArgs, buildTraceDependencyArgs, buildTraceCloneArgs, buildProjectInfoArgs, buildFeatureFlagsArgs, buildListBoundariesArgs, buildCheckRuntimeCoverageArgs, buildCheckChangedArgs, buildFixPreviewArgs, buildFixApplyArgs, buildExplainArgs, type CheckChangedParams, type FixParams, type ExplainParams } from './mcp/tool-builders.js';
export { discoverWorkspaces, findUndeclaredWorkspaces, parseTsconfigRootDir, type WorkspaceInfo, type WorkspaceDiagnostic, type WorkspaceConfig } from './config/workspace.js';
export { discoverExternalPlugins, mergePluginSuppressPatterns, PLUGIN_MANIFEST_KEY, type EntryPointRole, type ExternalUsedExport, type ExternalEntryPoint, type ExternalPluginDef } from './config/external-plugin.js';
export { DEFAULT_MONOGRAPH_CONFIG, type MonographConfig, type ResolvedMonographConfig, type ProductionAnalysis, type PerAnalysisProductionConfig, type ProductionConfigValue, type RegressionConfig, type AuditConfig, type DetectionMode, type NormalizationConfig, type BoundaryRule, type BoundaryZone, type BoundaryConfig, type ResolveConfig, type HealthConfig, type OwnershipConfig, type IgnoreExportRule, type ConfigOverride } from './config/types.js';
export { analyzeScripts, filterProductionScripts, parseScriptCommand, splitShellOperators, buildBinToPackageMap, analyzeCiFiles, type ScriptCommand, type ScriptAnalysis, type CiAnalysis } from './analysis/scripts.js';
export { pushExportDiagnostics, pushFileDiagnostics, pushImportDiagnostics, pushDepDiagnostics, pushMemberDiagnostics, pushCircularDepDiagnostics, pushBoundaryViolationDiagnostics, pushDuplicateExportDiagnostics, pushDuplicationDiagnostics, pushStaleSuppressionDiagnostics, type DiagnosticSeverity, type LspRange, type LspDiagnosticEntry, type DiagnosticMap, type UnusedExportFinding, type UnusedFileFinding, type UnresolvedImportFinding, type UnusedDepFinding, type UnusedMemberFinding, type CircularDepFinding, type BoundaryViolFinding, type DupeExportFinding, type DuplicationFinding, type StaleSuppressionFinding } from './lsp/diagnostics-push.js';
