/**
 * handlers/pick-core.cjs — the one-line [PICK] contract, system-prompt
 * detection, registry-only agent choice, honest route records, per-session
 * route files, pick adherence and the SessionStart skill-registry refresh.
 */
import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const PC_PATH = path.resolve(__dirname, '../../.claude/helpers/handlers/pick-core.cjs');
const pc = () => {
  delete require.cache[PC_PATH];
  return require(PC_PATH);
};

let tmp;
beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pick-core-'));
  fs.mkdirSync(path.join(tmp, '.monomind'), { recursive: true });
});
afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }));

const readJsonl = (f) =>
  fs.existsSync(f)
    ? fs
        .readFileSync(f, 'utf-8')
        .trim()
        .split('\n')
        .filter(Boolean)
        .map((l) => JSON.parse(l))
    : [];

describe('isSystemPrompt', () => {
  it.each([
    ['', true],
    ['   ', true],
    ['<task-notification>\n<task-id>x</task-id>\n</task-notification>', true],
    ['<system-reminder>ctx</system-reminder>\n  <system-reminder>more</system-reminder>', true],
    ['<command-name>/mastermind:do</command-name>\n<command-message>x</command-message>', true],
    ['<local-command-stdout>ok</local-command-stdout>', true],
    ['Caveat: The messages below were generated by the user while running local commands.', true],
    ['<system-reminder>ctx</system-reminder> fix the login bug', false],
    ['fix the login bug', false],
  ])('%j -> %s', (prompt, expected) => {
    expect(pc().isSystemPrompt(prompt)).toBe(expected);
  });

  it('treats non-strings as system prompts', () => {
    expect(pc().isSystemPrompt(undefined)).toBe(true);
  });
});

describe('prompt identity', () => {
  it('hashes to the first 16 hex chars of sha256', () => {
    const h = pc().promptHash('hello');
    expect(h).toBe('2cf24dba5fb0a30e');
  });

  it('previews at most 120 chars with secrets redacted', () => {
    const p = pc().promptPreview(`use sk-ant-${'a'.repeat(30)} to call ${'x'.repeat(300)}`);
    expect(p.length).toBeLessThanOrEqual(120);
    expect(p).not.toContain('sk-ant-');
    expect(p).toContain('[redacted]');
  });
});

describe('rankAgents / decide', () => {
  const agents = [
    { id: 'coder', name: 'coder', description: 'Writes code', text: '' },
    {
      id: 'engineering-security-engineer',
      name: 'Security Engineer',
      description: 'Threat modeling and vulnerability assessment',
      text: 'security-audit',
    },
    { id: 'security-engineer', name: 'security-engineer', description: 'dup', text: '' },
    { id: 'devops-automator', name: 'DevOps Automator', description: 'CI/CD', text: '' },
  ];
  const fakeJp = {
    shortlist: (q, items, limit) => {
      const words = q.toLowerCase().split(/\W+/);
      return items
        .map((it, index) => ({
          ...it,
          score:
            words.filter((w) => w && `${it.id} ${it.name}`.toLowerCase().includes(w)).length * 3,
          index,
        }))
        .sort((a, b) => b.score - a.score || a.index - b.index)
        .slice(0, limit);
    },
  };

  it('collapses candidates that share a normalised name and caps at 5', () => {
    const c = pc().rankAgents(fakeJp, 'security engineer review', agents);
    expect(c.length).toBeLessThanOrEqual(5);
    const names = c.map((x) => x.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'));
    expect(new Set(names).size).toBe(names.length);
    expect(c[0]).toMatchObject({ id: 'engineering-security-engineer', name: 'Security Engineer' });
  });

  it('prefers keywordRank when jev-picker exports one', () => {
    const jp = { ...fakeJp, keywordRank: () => [{ ...agents[3], score: 9 }] };
    expect(pc().rankAgents(jp, 'anything', agents)[0].id).toBe('devops-automator');
  });

  it('picks a keyword agent only on a strong, strictly leading score', () => {
    const { decide } = pc();
    const strong = decide({
      agents,
      keywordCands: [
        { id: 'devops-automator', name: 'DevOps Automator', score: 6 },
        { id: 'coder', name: 'coder', score: 3 },
      ],
    });
    expect(strong.agent).toEqual({ id: 'devops-automator', name: 'DevOps Automator' });
    expect(strong.method).toBe('keyword');
    const tie = decide({
      agents,
      keywordCands: [
        { id: 'a', name: 'A', score: 6 },
        { id: 'b', name: 'B', score: 6 },
      ],
    });
    expect(tie.agent).toBeNull();
    const weak = decide({ agents, keywordCands: [{ id: 'coder', name: 'coder', score: 3 }] });
    expect(weak.agent).toBeNull();
    expect(weak.method).toBe('none');
  });

  it('maps a Jev agent id to the registry frontmatter name', () => {
    const d = pc().decide({
      agents,
      keywordCands: [],
      jev: {
        provider: 'custom',
        agent: 'engineering-security-engineer',
        agentConfidence: 0.9,
        agentRanked: [
          { id: 'engineering-security-engineer', probability: 0.9 },
          { id: 'coder', probability: 0.1 },
        ],
        skillAnswered: true,
        skills: [{ id: 'security-review', invoke: 'Skill("security-review")' }],
      },
    });
    expect(d.agent).toEqual({ id: 'engineering-security-engineer', name: 'Security Engineer' });
    expect(d.skill).toEqual({ skill: 'security-review', invoke: 'Skill("security-review")' });
    expect(d).toMatchObject({ method: 'jev', provider: 'custom', confidence: 0.9 });
    expect(d.candidates[0]).toEqual({ name: 'Security Engineer', score: 0.9 });
  });

  it('never returns an agent id that is not in the registry', () => {
    const d = pc().decide({
      agents,
      keywordCands: [],
      jev: { agent: 'made-up', agentConfidence: 1 },
    });
    expect(d.agent).toBeNull();
  });

  it('a confident Jev "no skill fits" suppresses keyword skill matches', () => {
    const d = pc().decide({
      agents,
      keywordCands: [],
      skillMatches: [{ skill: 'tokens', invoke: '/tokens', score: 5 }],
      jev: { skillAnswered: true, skills: [] },
    });
    expect(d.skill).toBeNull();
  });

  it('picks a keyword skill only on a strong, strictly leading score', () => {
    const { decide } = pc();
    expect(
      decide({
        agents,
        keywordCands: [],
        skillMatches: [{ skill: 'tokens', invoke: '/tokens', score: 5 }],
      }).skill,
    ).toEqual({ skill: 'tokens', invoke: '/tokens' });
    expect(
      decide({
        agents,
        keywordCands: [],
        skillMatches: [
          { skill: 'a', invoke: '/a', score: 4 },
          { skill: 'b', invoke: '/b', score: 4 },
        ],
      }).skill,
    ).toBeNull();
    expect(
      decide({ agents, keywordCands: [], skillMatches: [{ skill: 'a', invoke: '/a', score: 3 }] })
        .skill,
    ).toBeNull();
  });
});

describe('formatPickLine', () => {
  const { formatPickLine } = pc();
  it('prints both parts, one part, or nothing', () => {
    expect(
      formatPickLine({
        agent: { name: 'Security Engineer' },
        skill: { invoke: '/security-review' },
      }),
    ).toBe('[PICK] agent: Security Engineer · skill: /security-review');
    expect(formatPickLine({ agent: null, skill: { invoke: '/tokens' } })).toBe(
      '[PICK] skill: /tokens',
    );
    expect(formatPickLine({ agent: { name: 'coder' }, skill: null })).toBe('[PICK] agent: coder');
    expect(formatPickLine({ agent: null, skill: null })).toBe('');
  });
});

describe('persistRoute', () => {
  const pick = {
    agent: { id: 'engineering-security-engineer', name: 'Security Engineer' },
    skill: { skill: 'security-review', invoke: 'Skill("security-review")' },
    method: 'jev',
    provider: 'custom',
    confidence: 0.9,
    candidates: [{ name: 'Security Engineer', score: 0.9 }],
  };

  it('writes an honest outcome record without raw prompt text', () => {
    const prompt = `audit the auth flow ${'z'.repeat(400)}`;
    const routeId = pc().persistRoute(tmp, { pick, prompt, sessionId: 'sess-A', shown: true });
    const [rec] = readJsonl(path.join(tmp, '.monomind', 'route-outcomes.jsonl'));
    expect(rec).toMatchObject({
      routeId,
      sessionId: 'sess-A',
      promptHash: pc().promptHash(prompt),
      agentName: 'Security Engineer',
      agentId: 'engineering-security-engineer',
      skill: 'Skill("security-review")',
      method: 'jev',
      provider: 'custom',
      confidence: 0.9,
      shown: true,
      recommendedAgent: 'Security Engineer',
      routingMethod: 'jev',
    });
    expect(rec.promptPreview.length).toBeLessThanOrEqual(120);
    expect(JSON.stringify(rec)).not.toContain('z'.repeat(200));
    expect(rec.candidates).toEqual(pick.candidates);
    expect(typeof rec.ts).toBe('number');
  });

  it('keeps one route file per session so concurrent sessions do not clobber', () => {
    const { persistRoute, readSessionRoute } = pc();
    const a = persistRoute(tmp, { pick, prompt: 'one', sessionId: 'sess-A', shown: true });
    const b = persistRoute(tmp, {
      pick: { ...pick, agent: null },
      prompt: 'two',
      sessionId: 'sess-B',
      shown: false,
    });
    expect(readSessionRoute(tmp, 'sess-A')).toMatchObject({
      routeId: a,
      agent: 'Security Engineer',
    });
    expect(readSessionRoute(tmp, 'sess-B')).toMatchObject({ routeId: b, agent: null });
    // last-route.json stays the latest route (statusline), now carrying its session.
    const last = JSON.parse(
      fs.readFileSync(path.join(tmp, '.monomind', 'last-route.json'), 'utf-8'),
    );
    expect(last).toMatchObject({ routeId: b, sessionId: 'sess-B' });
  });

  it('sanitises the session id used as a file name', () => {
    pc().persistRoute(tmp, { pick, prompt: 'x', sessionId: '../../evil', shown: false });
    expect(fs.readdirSync(path.join(tmp, '.monomind', 'routes'))).toEqual(['evil.json']);
  });
});

describe('recordAdherence', () => {
  it('records the recommendation against the spawned subagent_type and joins the outcome', () => {
    const { persistRoute, recordAdherence } = pc();
    const routeId = persistRoute(tmp, {
      pick: {
        agent: { id: 'engineering-security-engineer', name: 'Security Engineer' },
        skill: null,
        method: 'jev',
        provider: 'custom',
        confidence: 0.9,
        candidates: [],
      },
      prompt: 'audit',
      sessionId: 'sess-A',
      shown: true,
    });
    recordAdherence(tmp, {
      session_id: 'sess-A',
      tool_name: 'Task',
      tool_input: { subagent_type: 'coder' },
    });
    recordAdherence(tmp, {
      session_id: 'sess-A',
      tool_name: 'Agent',
      tool_input: { subagent_type: 'Security Engineer' },
    });
    const adh = readJsonl(path.join(tmp, '.monomind', 'pick-adherence.jsonl'));
    expect(adh).toHaveLength(2);
    expect(adh[0]).toMatchObject({
      routeId,
      sessionId: 'sess-A',
      recommended: 'Security Engineer',
      actual: 'coder',
      followed: false,
    });
    expect(adh[1]).toMatchObject({ actual: 'Security Engineer', followed: true });
    const [rec] = readJsonl(path.join(tmp, '.monomind', 'route-outcomes.jsonl'));
    // The first spawn after the pick is the one that answers it.
    expect(rec.agentActuallyUsed).toBe('coder');
  });

  it('records followed: null when there was no recommendation', () => {
    pc().recordAdherence(tmp, { session_id: 'nope', tool_input: { subagent_type: 'coder' } });
    const [a] = readJsonl(path.join(tmp, '.monomind', 'pick-adherence.jsonl'));
    expect(a).toMatchObject({ routeId: null, recommended: null, actual: 'coder', followed: null });
  });
});

describe('ensureSkillRegistryFresh', () => {
  function makeSkill(name) {
    const d = path.join(tmp, '.claude', 'skills', name);
    fs.mkdirSync(d, { recursive: true });
    fs.writeFileSync(
      path.join(d, 'SKILL.md'),
      `---\nname: ${name}\ndescription: ${name} skill\n---\n`,
    );
  }
  const builder = {
    build: (root) => ({
      skills: fs.readdirSync(path.join(root, '.claude', 'skills')).map((s) => ({ skill: s })),
    }),
  };
  const reg = () => path.join(tmp, '.claude', 'helpers', 'skill-registry.json');

  it('builds the registry when it is missing', () => {
    makeSkill('alpha');
    expect(pc().ensureSkillRegistryFresh(tmp, builder)).toBe('rebuilt');
    expect(JSON.parse(fs.readFileSync(reg(), 'utf-8')).skills).toEqual([{ skill: 'alpha' }]);
  });

  it('rebuilds when a SKILL.md is newer and skips when fresh', () => {
    makeSkill('alpha');
    const { ensureSkillRegistryFresh } = pc();
    ensureSkillRegistryFresh(tmp, builder);
    const past = new Date(Date.now() - 60_000);
    fs.utimesSync(reg(), past, past);
    fs.utimesSync(path.join(tmp, '.claude', 'skills'), past, past);
    fs.utimesSync(path.join(tmp, '.claude', 'skills', 'alpha'), past, past);
    fs.utimesSync(path.join(tmp, '.claude', 'skills', 'alpha', 'SKILL.md'), past, past);
    expect(ensureSkillRegistryFresh(tmp, builder)).toBe('fresh');
    fs.utimesSync(path.join(tmp, '.claude', 'skills', 'alpha', 'SKILL.md'), new Date(), new Date());
    expect(ensureSkillRegistryFresh(tmp, builder)).toBe('rebuilt');
  });

  it('reports a builder without a build export instead of crashing', () => {
    makeSkill('alpha');
    expect(pc().ensureSkillRegistryFresh(tmp, {})).toBe('no-builder');
  });

  it('does nothing when the project has no skills tree', () => {
    expect(pc().ensureSkillRegistryFresh(tmp, builder)).toBe('no-skills');
  });
});
