/**
 * handlers/pick-core.cjs — the one-line [PICK] contract, system-prompt
 * detection, registry-only agent choice, honest route records, per-session
 * route files, pick adherence and the SessionStart skill-registry refresh.
 */
import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const PC_PATH = path.resolve(__dirname, '../../.claude/helpers/handlers/pick-core.cjs');
const pc = () => {
  delete require.cache[PC_PATH];
  return require(PC_PATH);
};

let tmp;
beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pick-core-'));
  fs.mkdirSync(path.join(tmp, '.monomind'), { recursive: true });
});
afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }));

const readJsonl = (f) =>
  fs.existsSync(f)
    ? fs
        .readFileSync(f, 'utf-8')
        .trim()
        .split('\n')
        .filter(Boolean)
        .map((l) => JSON.parse(l))
    : [];

describe('isSystemPrompt', () => {
  it.each([
    ['', true],
    ['   ', true],
    ['<task-notification>\n<task-id>x</task-id>\n</task-notification>', true],
    ['<system-reminder>ctx</system-reminder>\n  <system-reminder>more</system-reminder>', true],
    ['<command-name>/mastermind:do</command-name>\n<command-message>x</command-message>', true],
    ['<local-command-stdout>ok</local-command-stdout>', true],
    ['Caveat: The messages below were generated by the user while running local commands.', true],
    ['<system-reminder>ctx</system-reminder> fix the login bug', false],
    ['fix the login bug', false],
  ])('%j -> %s', (prompt, expected) => {
    expect(pc().isSystemPrompt(prompt)).toBe(expected);
  });

  it('treats non-strings as system prompts', () => {
    expect(pc().isSystemPrompt(undefined)).toBe(true);
  });
});

describe('prompt identity', () => {
  it('hashes to the first 16 hex chars of sha256', () => {
    const h = pc().promptHash('hello');
    expect(h).toBe('2cf24dba5fb0a30e');
  });

  it('previews at most 120 chars with secrets redacted', () => {
    const p = pc().promptPreview(`use sk-ant-${'a'.repeat(30)} to call ${'x'.repeat(300)}`);
    expect(p.length).toBeLessThanOrEqual(120);
    expect(p).not.toContain('sk-ant-');
    expect(p).toContain('[redacted]');
  });
});

describe('rankAgents / decide', () => {
  const agents = [
    { id: 'coder', name: 'coder', description: 'Writes code', text: '' },
    {
      id: 'engineering-security-engineer',
      name: 'Security Engineer',
      description: 'Threat modeling and vulnerability assessment',
      text: 'security-audit',
    },
    { id: 'security-engineer', name: 'security-engineer', description: 'dup', text: '' },
    { id: 'devops-automator', name: 'DevOps Automator', description: 'CI/CD', text: '' },
  ];
  const fakeJp = {
    shortlist: (q, items, limit) => {
      const words = q.toLowerCase().split(/\W+/);
      return items
        .map((it, index) => ({
          ...it,
          score:
            words.filter((w) => w && `${it.id} ${it.name}`.toLowerCase().includes(w)).length * 3,
          index,
        }))
        .sort((a, b) => b.score - a.score || a.index - b.index)
        .slice(0, limit);
    },
  };

  it('collapses candidates that share a normalised name and caps at 5', () => {
    const c = pc().rankAgents(fakeJp, 'security engineer review', agents);
    expect(c.length).toBeLessThanOrEqual(5);
    const names = c.map((x) => x.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'));
    expect(new Set(names).size).toBe(names.length);
    expect(c[0]).toMatchObject({ id: 'engineering-security-engineer', name: 'Security Engineer' });
  });

  it('prefers keywordRank when jev-picker exports one', () => {
    const jp = { ...fakeJp, keywordRank: () => [{ ...agents[3], score: 9 }] };
    expect(pc().rankAgents(jp, 'anything', agents)[0].id).toBe('devops-automator');
  });

  it('re-ranks candidates by the outcome prior and keeps the base score', () => {
    const jp = {
      keywordRank: () => [
        { ...agents[0], score: 3.0 },
        { ...agents[3], score: 2.9 },
      ],
    };
    const stats = {
      agents: { 'devops-automator': { name: 'DevOps Automator', success: 20, followed: 20 } },
    };
    const c = pc().rankAgents(jp, 'anything', agents, stats);
    expect(c[0]).toMatchObject({ id: 'devops-automator', baseScore: 2.9 });
    expect(c[0].prior).toBeGreaterThan(1);
    expect(pc().rankAgents(jp, 'anything', agents)[0].id).toBe('coder');
  });

  it('holds the keyword floor on relevance, not on a prior-boosted score', () => {
    const d = pc().decide({
      agents,
      keywordCands: [{ id: 'coder', name: 'coder', score: 2.2, baseScore: 1.9, prior: 1.15 }],
    });
    expect(d.agent).toBeNull();
  });

  it('picks a keyword agent only on a strong, strictly leading score', () => {
    const { decide } = pc();
    const strong = decide({
      agents,
      keywordCands: [
        { id: 'devops-automator', name: 'DevOps Automator', score: 6 },
        { id: 'coder', name: 'coder', score: 3 },
      ],
    });
    expect(strong.agent).toEqual({ id: 'devops-automator', name: 'DevOps Automator' });
    expect(strong.method).toBe('keyword');
    const tie = decide({
      agents,
      keywordCands: [
        { id: 'a', name: 'A', score: 6 },
        { id: 'b', name: 'B', score: 6 },
      ],
    });
    expect(tie.agent).toBeNull();
    const weak = decide({ agents, keywordCands: [{ id: 'coder', name: 'coder', score: 1.5 }] });
    expect(weak.agent).toBeNull();
    expect(weak.method).toBe('none');
  });

  it('maps a Jev agent id to the registry frontmatter name', () => {
    const d = pc().decide({
      agents,
      keywordCands: [],
      jev: {
        provider: 'custom',
        agent: 'engineering-security-engineer',
        agentConfidence: 0.9,
        agentRanked: [
          { id: 'engineering-security-engineer', probability: 0.9 },
          { id: 'coder', probability: 0.1 },
        ],
        skillAnswered: true,
        skills: [{ id: 'security-review', invoke: 'Skill("security-review")' }],
      },
    });
    expect(d.agent).toEqual({ id: 'engineering-security-engineer', name: 'Security Engineer' });
    expect(d.skill).toEqual({ skill: 'security-review', invoke: 'Skill("security-review")' });
    expect(d).toMatchObject({ method: 'jev', provider: 'custom', confidence: 0.9 });
    expect(d.candidates[0]).toEqual({ name: 'Security Engineer', score: 0.9 });
  });

  it('never returns an agent id that is not in the registry', () => {
    const d = pc().decide({
      agents,
      keywordCands: [],
      jev: { agent: 'made-up', agentConfidence: 1 },
    });
    expect(d.agent).toBeNull();
  });

  it('a confident Jev "no skill fits" suppresses keyword skill matches', () => {
    const d = pc().decide({
      agents,
      keywordCands: [],
      skillMatches: [{ skill: 'tokens', invoke: '/tokens', score: 5 }],
      jev: { skillAnswered: true, skills: [] },
    });
    expect(d.skill).toBeNull();
  });

  it('picks a keyword skill only above the floor and with a clear lead', () => {
    const { decide, KEYWORD_MIN_SKILL_SCORE, KEYWORD_SKILL_LEAD } = pc();
    expect(KEYWORD_MIN_SKILL_SCORE).toBe(3);
    expect(KEYWORD_SKILL_LEAD).toBe(1.25);
    const skill = (skillMatches) => decide({ agents, keywordCands: [], skillMatches }).skill;
    expect(skill([{ skill: 'tokens', invoke: '/tokens', score: 5 }])).toEqual({
      skill: 'tokens',
      invoke: '/tokens',
    });
    expect(
      skill([
        { skill: 'a', invoke: '/a', score: 4 },
        { skill: 'b', invoke: '/b', score: 4 },
      ]),
    ).toBeNull();
    expect(
      skill([
        { skill: 'a', invoke: '/a', score: 5 },
        { skill: 'b', invoke: '/b', score: 4.5 },
      ]),
    ).toBeNull();
    expect(
      skill([
        { skill: 'a', invoke: '/a', score: 5 },
        { skill: 'b', invoke: '/b', score: 3.9 },
      ]),
    ).toEqual({ skill: 'a', invoke: '/a' });
    expect(skill([{ skill: 'a', invoke: '/a', score: 2.9 }])).toBeNull();
  });
});

describe('rankSkills', () => {
  const jp = require(path.resolve(__dirname, '../../.claude/helpers/jev-picker.cjs'));
  const skills = [
    {
      id: 'security-review',
      invoke: 'Skill("security-review")',
      description: 'Review code for security vulnerabilities',
      source: 'platform',
    },
    {
      id: 'threat-model',
      invoke: 'mcp__monomind__org_skill_show {"name":"threat-model"}',
      description: 'Threat modeling of an architecture for security risks',
      source: 'org',
    },
    {
      id: 'skill-admin',
      invoke: 'Skill("skill-admin")',
      description: 'Security review settings for skills',
      source: 'platform',
      pick: 'low',
    },
    {
      id: 'copywriting',
      invoke: 'Skill("copywriting")',
      description: 'Marketing copy',
      source: 'platform',
    },
  ];

  it('ranks the shared skill catalog (org skills included) with pick-rank, zero scores dropped', () => {
    const got = pc().rankSkills(jp, 'threat modeling for the payments architecture', skills);
    expect(got[0]).toMatchObject({
      skill: 'threat-model',
      invoke: 'mcp__monomind__org_skill_show {"name":"threat-model"}',
    });
    expect(got[0].score).toBeGreaterThan(0);
    expect(got.map((m) => m.skill)).not.toContain('copywriting');
  });

  it('keeps a pick: low skill below an equally matching one', () => {
    const got = pc()
      .rankSkills(jp, 'security review', skills)
      .map((m) => m.skill);
    expect(got.indexOf('security-review')).toBeLessThan(got.indexOf('skill-admin'));
  });

  it('returns [] without a picker or catalog', () => {
    expect(pc().rankSkills(null, 'security review', skills)).toEqual([]);
    expect(pc().rankSkills(jp, 'security review', [])).toEqual([]);
  });
});

describe('formatPickLine', () => {
  const { formatPickLine } = pc();
  it('prints both parts, one part, or nothing', () => {
    expect(
      formatPickLine({
        agent: { name: 'Security Engineer' },
        skill: { invoke: '/security-review' },
      }),
    ).toBe('[PICK] agent: Security Engineer · skill: /security-review');
    expect(formatPickLine({ agent: null, skill: { invoke: '/tokens' } })).toBe(
      '[PICK] skill: /tokens',
    );
    expect(formatPickLine({ agent: { name: 'coder' }, skill: null })).toBe('[PICK] agent: coder');
    expect(formatPickLine({ agent: null, skill: null })).toBe('');
  });
});

describe('persistRoute', () => {
  const pick = {
    agent: { id: 'engineering-security-engineer', name: 'Security Engineer' },
    skill: { skill: 'security-review', invoke: 'Skill("security-review")' },
    method: 'jev',
    provider: 'custom',
    confidence: 0.9,
    candidates: [{ name: 'Security Engineer', score: 0.9 }],
  };

  it('writes an honest outcome record without raw prompt text', () => {
    const prompt = `audit the auth flow ${'z'.repeat(400)}`;
    const routeId = pc().persistRoute(tmp, { pick, prompt, sessionId: 'sess-A', shown: true });
    const [rec] = readJsonl(path.join(tmp, '.monomind', 'route-outcomes.jsonl'));
    expect(rec).toMatchObject({
      routeId,
      sessionId: 'sess-A',
      promptHash: pc().promptHash(prompt),
      agentName: 'Security Engineer',
      agentId: 'engineering-security-engineer',
      skill: 'Skill("security-review")',
      method: 'jev',
      provider: 'custom',
      confidence: 0.9,
      shown: true,
      recommendedAgent: 'Security Engineer',
      routingMethod: 'jev',
    });
    expect(rec.promptPreview.length).toBeLessThanOrEqual(120);
    expect(JSON.stringify(rec)).not.toContain('z'.repeat(200));
    expect(rec.candidates).toEqual(pick.candidates);
    expect(typeof rec.ts).toBe('number');
  });

  it('keeps one route file per session so concurrent sessions do not clobber', () => {
    const { persistRoute, readSessionRoute } = pc();
    const a = persistRoute(tmp, { pick, prompt: 'one', sessionId: 'sess-A', shown: true });
    const b = persistRoute(tmp, {
      pick: { ...pick, agent: null },
      prompt: 'two',
      sessionId: 'sess-B',
      shown: false,
    });
    expect(readSessionRoute(tmp, 'sess-A')).toMatchObject({
      routeId: a,
      agent: 'Security Engineer',
    });
    expect(readSessionRoute(tmp, 'sess-B')).toMatchObject({ routeId: b, agent: null });
    // last-route.json stays the latest route (statusline), now carrying its session.
    const last = JSON.parse(
      fs.readFileSync(path.join(tmp, '.monomind', 'last-route.json'), 'utf-8'),
    );
    expect(last).toMatchObject({ routeId: b, sessionId: 'sess-B' });
  });

  it('sanitises the session id used as a file name', () => {
    pc().persistRoute(tmp, { pick, prompt: 'x', sessionId: '../../evil', shown: false });
    expect(fs.readdirSync(path.join(tmp, '.monomind', 'routes'))).toEqual(['evil.json']);
  });
});

describe('recordAdherence', () => {
  it('records the recommendation against the spawned subagent_type and joins the outcome', () => {
    const { persistRoute, recordAdherence } = pc();
    const routeId = persistRoute(tmp, {
      pick: {
        agent: { id: 'engineering-security-engineer', name: 'Security Engineer' },
        skill: null,
        method: 'jev',
        provider: 'custom',
        confidence: 0.9,
        candidates: [],
      },
      prompt: 'audit',
      sessionId: 'sess-A',
      shown: true,
    });
    recordAdherence(tmp, {
      session_id: 'sess-A',
      tool_name: 'Task',
      tool_input: { subagent_type: 'coder' },
    });
    recordAdherence(tmp, {
      session_id: 'sess-A',
      tool_name: 'Agent',
      tool_input: { subagent_type: 'Security Engineer' },
    });
    const adh = readJsonl(path.join(tmp, '.monomind', 'pick-adherence.jsonl'));
    expect(adh).toHaveLength(2);
    expect(adh[0]).toMatchObject({
      routeId,
      sessionId: 'sess-A',
      recommended: 'Security Engineer',
      actual: 'coder',
      followed: false,
    });
    expect(adh[1]).toMatchObject({ actual: 'Security Engineer', followed: true });
    const [rec] = readJsonl(path.join(tmp, '.monomind', 'route-outcomes.jsonl'));
    // The first spawn after the pick is the one that answers it.
    expect(rec.agentActuallyUsed).toBe('coder');
  });

  it('records followed: null when there was no recommendation', () => {
    pc().recordAdherence(tmp, { session_id: 'nope', tool_input: { subagent_type: 'coder' } });
    const [a] = readJsonl(path.join(tmp, '.monomind', 'pick-adherence.jsonl'));
    expect(a).toMatchObject({ routeId: null, recommended: null, actual: 'coder', followed: null });
  });
});

describe('ensureSkillRegistryFresh', () => {
  const reg = () => path.join(tmp, '.claude', 'helpers', 'skill-registry.json');

  it("asks build-skill-registry's isStale and rebuilds through its ensure", () => {
    const calls = [];
    const builder = {
      isStale: (root) => (calls.push(['isStale', root]), true),
      ensure: (root) => calls.push(['ensure', root]),
    };
    expect(pc().ensureSkillRegistryFresh(tmp, builder)).toBe('rebuilt');
    expect(calls).toEqual([
      ['isStale', tmp],
      ['ensure', tmp],
    ]);
    expect(pc().ensureSkillRegistryFresh(tmp, { isStale: () => false, ensure: () => {} })).toBe(
      'fresh',
    );
  });

  it('reports a builder without isStale/ensure instead of crashing', () => {
    expect(pc().ensureSkillRegistryFresh(tmp, { build: () => ({}) })).toBe('no-builder');
    expect(pc().ensureSkillRegistryFresh(tmp, null)).toBe('no-builder');
  });

  it('rebuilds for a new slash command, not only for .claude/skills changes', () => {
    const cmds = path.join(tmp, '.claude', 'commands');
    fs.mkdirSync(cmds, { recursive: true });
    fs.writeFileSync(path.join(cmds, 'alpha.md'), '---\ndescription: alpha command\n---\n');
    const { ensureSkillRegistryFresh } = pc();
    expect(ensureSkillRegistryFresh(tmp)).toBe('rebuilt');
    const past = new Date(Date.now() + 60_000);
    fs.utimesSync(reg(), past, past);
    expect(ensureSkillRegistryFresh(tmp)).toBe('fresh');
    const later = new Date(Date.now() + 120_000);
    fs.writeFileSync(path.join(cmds, 'beta.md'), '---\ndescription: beta command\n---\n');
    fs.utimesSync(path.join(cmds, 'beta.md'), later, later);
    expect(ensureSkillRegistryFresh(tmp)).toBe('rebuilt');
  });
});

describe('route-outcomes under concurrent sessions', () => {
  it('loses no route record when two processes append and join at once', async () => {
    const { spawn } = await import('node:child_process');
    const N = 150;
    const worker = `
      const pc = require(${JSON.stringify(PC_PATH)});
      const [cwd, sid, n] = process.argv.slice(1);
      const pick = { agent: { id: 'coder', name: 'coder' }, skill: null, method: 'keyword',
        provider: null, confidence: null, candidates: [] };
      for (let i = 0; i < Number(n); i++) {
        pc.persistRoute(cwd, { pick, prompt: sid + ' task ' + i, sessionId: sid, shown: true });
        pc.recordAdherence(cwd, { session_id: sid, tool_name: 'Task', tool_input: { subagent_type: 'coder' } });
      }
    `;
    const run = (sid) =>
      new Promise((resolve, reject) => {
        const p = spawn(process.execPath, ['-e', worker, tmp, sid, String(N)], {
          stdio: 'inherit',
        });
        p.on('error', reject);
        p.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`exit ${code}`))));
      });
    await Promise.all([run('sess-A'), run('sess-B')]);
    const recs = readJsonl(path.join(tmp, '.monomind', 'route-outcomes.jsonl'));
    expect(recs.filter((r) => r.sessionId === 'sess-A')).toHaveLength(N);
    expect(recs.filter((r) => r.sessionId === 'sess-B')).toHaveLength(N);
    expect(recs.filter((r) => r.agentActuallyUsed === 'coder')).toHaveLength(2 * N);
    expect(fs.existsSync(path.join(tmp, '.monomind', 'route-outcomes.jsonl.lock'))).toBe(false);
  }, 60_000);

  it('rotates the log down to the newest records under the lock', () => {
    const f = path.join(tmp, '.monomind', 'route-outcomes.jsonl');
    const big = `${JSON.stringify({ routeId: 'old', pad: 'x'.repeat(2000) })}\n`;
    fs.writeFileSync(f, big.repeat(300));
    const pick = {
      agent: null,
      skill: null,
      method: 'none',
      provider: null,
      confidence: null,
      candidates: [],
    };
    const id = pc().persistRoute(tmp, { pick, prompt: 'p', sessionId: 's', shown: false });
    const recs = readJsonl(f);
    expect(recs.length).toBeLessThanOrEqual(500);
    expect(recs.at(-1).routeId).toBe(id);
    expect(fs.statSync(f).size).toBeLessThan(512 * 1024);
  });

  it('breaks a stale lock instead of waiting on it forever', () => {
    const lock = path.join(tmp, '.monomind', 'route-outcomes.jsonl.lock');
    fs.writeFileSync(lock, '999999');
    const past = new Date(Date.now() - 60_000);
    fs.utimesSync(lock, past, past);
    const pick = {
      agent: null,
      skill: null,
      method: 'none',
      provider: null,
      confidence: null,
      candidates: [],
    };
    const id = pc().persistRoute(tmp, { pick, prompt: 'p', sessionId: 's', shown: false });
    expect(pc().joinOutcome(tmp, id, { measuredSuccess: true })).toBe(true);
    expect(readJsonl(path.join(tmp, '.monomind', 'route-outcomes.jsonl')).at(-1)).toMatchObject({
      routeId: id,
      measuredSuccess: true,
    });
    expect(fs.existsSync(lock)).toBe(false);
  });
});

describe('slash-command routes', () => {
  it('a route without an agent recommendation (slash command) is not adherence data', () => {
    const { persistCommandRoute, recordAdherence } = pc();
    persistCommandRoute(tmp, { command: '/ts', sessionId: 'sess-A' });
    const last = JSON.parse(
      fs.readFileSync(path.join(tmp, '.monomind', 'last-route.json'), 'utf-8'),
    );
    expect(last).toMatchObject({ agent: null, skill: '/ts', sessionId: 'sess-A' });
    const rec = recordAdherence(tmp, {
      session_id: 'sess-A',
      tool_name: 'Task',
      tool_input: { subagent_type: 'coder' },
    });
    expect(rec).toMatchObject({ recommended: null, followed: null });
  });

  it("never answers with another session's route, even a legacy one without a session", () => {
    const { readSessionRoute, recordAdherence } = pc();
    fs.writeFileSync(
      path.join(tmp, '.monomind', 'last-route.json'),
      JSON.stringify({ agent: '/ts', confidence: 1, reason: 'predefined command' }),
    );
    expect(readSessionRoute(tmp, 'sess-B')).toBeNull();
    const rec = recordAdherence(tmp, {
      session_id: 'sess-B',
      tool_name: 'Task',
      tool_input: { subagent_type: 'coder' },
    });
    expect(rec).toMatchObject({ recommended: null, followed: null });
  });
});
