import type { MonographNode, MonographEdge } from '../types.js';

export function toCypher(nodes: MonographNode[], edges: MonographEdge[]): string {
  const lines: string[] = [
    '// Generated by Monograph — read-only import script',
    '// Only CREATE statements; no DROP/DELETE operations',
    '',
  ];

  for (const n of nodes) {
    const props = `{id: ${q(n.id)}, name: ${q(n.name)}, file: ${q(n.filePath ?? '')}, exported: ${n.isExported}}`;
    lines.push(`CREATE (n_${safe(n.id)}:${n.label} ${props})`);
  }

  lines.push('');

  for (const e of edges) {
    lines.push(
      `MATCH (a {id: ${q(e.sourceId)}}), (b {id: ${q(e.targetId)}}) ` +
        `CREATE (a)-[:${e.relation} {confidence: ${q(e.confidence)}}]->(b)`
    );
  }

  return lines.join('\n');
}

function q(s: string): string {
  return `"${s.replace(/"/g, '\\"')}"`;
}

function safe(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, '_');
}
