import { describe, it, expect, beforeEach } from 'vitest';
import { toJson } from '../../src/export/json.js';
import { toCypher } from '../../src/export/cypher.js';
import type { MonographNode, MonographEdge } from '../../src/types.js';

let nodes: MonographNode[];
let edges: MonographEdge[];

beforeEach(() => {
  nodes = [
    { id: 'n1', label: 'Class', name: 'Foo', normLabel: 'foo', isExported: true },
    { id: 'n2', label: 'Method', name: 'bar', normLabel: 'bar', isExported: false, filePath: 'foo.ts' },
  ];
  edges = [
    { id: 'e1', sourceId: 'n1', targetId: 'n2', relation: 'CONTAINS', confidence: 'EXTRACTED', confidenceScore: 1.0 },
    { id: 'e2', sourceId: 'n2', targetId: 'n1', relation: 'CALLS', confidence: 'INFERRED', confidenceScore: 0.5 },
  ];
});

describe('json export', () => {
  it('produces nodes and edges fields', () => {
    const result = toJson(nodes, edges);
    const parsed = JSON.parse(result);
    expect(parsed.nodes).toHaveLength(2);
    expect(parsed.edges).toHaveLength(2);
  });

  it('transforms node properties correctly', () => {
    const result = toJson(nodes, edges);
    const parsed = JSON.parse(result);
    const firstNode = parsed.nodes[0];
    expect(firstNode.id).toBe('n1');
    expect(firstNode.label).toBe('Class');
    expect(firstNode.norm_label).toBe('foo');
    expect(firstNode.is_exported).toBe(true);
  });

  it('includes links array', () => {
    const result = toJson(nodes, edges);
    const parsed = JSON.parse(result);
    expect(parsed.links).toBeDefined();
    expect(parsed.links).toHaveLength(2);
  });
});

describe('cypher export', () => {
  it('does not include destructive operations', () => {
    const result = toCypher(nodes, edges);
    expect(result).toContain('CREATE');
    // Verify no standalone destructive operations (DROP/DELETE statements, not in comments)
    const lines = result.split('\n').filter(l => !l.trim().startsWith('//'));
    expect(lines.some(l => l.includes('DROP'))).toBe(false);
    expect(lines.some(l => l.includes('DELETE'))).toBe(false);
  });

  it('includes comment header', () => {
    const result = toCypher(nodes, edges);
    expect(result).toContain('// Generated by Monograph');
  });

  it('creates nodes and edges separately', () => {
    const result = toCypher(nodes, edges);
    const lines = result.split('\n');
    const createNodeLines = lines.filter(l => l.includes('CREATE') && l.includes(':'));
    expect(createNodeLines.length).toBeGreaterThan(0);
  });

  it('handles special characters safely', () => {
    const nodeWithSpecial = {
      ...nodes[0],
      name: 'Foo"Bar"Baz',
      id: 'n-special_id',
    };
    const result = toCypher([nodeWithSpecial], []);
    // Verify escaped quotes in output
    expect(result).toContain('\\"');
    // Verify it doesn't have unescaped double quotes in the middle
    const lines = result.split('\n');
    const createLines = lines.filter(l => l.includes('CREATE') && l.includes('name:'));
    expect(createLines.length).toBeGreaterThan(0);
  });
});
