import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, beforeAll } from 'vitest';
import { Language, Parser } from 'web-tree-sitter';

/**
 * ABI gate for the vendored WASM grammars (wasm/manifest.json, generated by
 * scripts/refresh-wasm.mjs). Every manifest entry must load under
 * web-tree-sitter and bind to a Parser — a failure here means a grammar was
 * refreshed from an incompatible source (e.g. a tree-sitter ABI outside
 * web-tree-sitter's supported range) and would silently degrade every parse
 * of that language in production.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmDir = join(__dirname, '../../wasm');
const manifest = JSON.parse(readFileSync(join(wasmDir, 'manifest.json'), 'utf8')) as Record<
  string,
  { file: string; source: string }
>;

describe('vendored wasm grammar manifest', () => {
  beforeAll(async () => {
    await Parser.init();
  });

  it('covers every language config except vue (which reuses the TS grammar)', () => {
    // 14 wasm grammars: the 12 package-shipped ones + dart/kotlin/swift built
    // from source. vue intentionally shares tree-sitter-typescript.wasm.
    expect(Object.keys(manifest)).toHaveLength(14);
    expect(manifest.vue).toBeUndefined();
  });

  it('every manifest entry has its wasm file present and loadable', async () => {
    for (const [name, entry] of Object.entries(manifest)) {
      const path = join(wasmDir, entry.file);
      expect(existsSync(path), `${name}: ${entry.file} missing`).toBe(true);

      const lang = await Language.load(readFileSync(path));
      const parser = new Parser();
      expect(() => parser.setLanguage(lang), `${name}: ABI bind failed`).not.toThrow();
      expect(() => parser.parse('smoke'), `${name}: parse failed`).not.toThrow();
      parser.delete();
    }
  });

  it('records the source package for traceability', () => {
    for (const [name, entry] of Object.entries(manifest)) {
      expect(entry.source, name).toMatch(/@\d+\.\d+\.\d+/);
    }
  });
});
