import type { Route } from '../types.js';

export const marketingRoutes: Route[] = [
  {
    name: 'seo-specialist',
    agentSlug: 'Competitive Content Strategist',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'SEO optimization, keyword research, content strategy for search',
    utterances: [
      'optimize the landing page for search engine rankings',
      'perform keyword research for the product category',
      'audit the technical SEO issues on the website',
      'create the content strategy for improving organic traffic',
      'optimize the meta titles and descriptions for the blog posts',
      'build the internal linking strategy for the content hub',
      'analyze the backlink profile and create a link building plan',
      'optimize the page speed for better core web vitals scores',
      'create the schema markup for the product pages',
      'analyze competitors SEO strategy and find ranking opportunities',
    ],
  },
  {
    name: 'content-creator',
    agentSlug: 'Competitive Content Strategist',
    threshold: 0.7,
    fallbackToLLM: true,
    description: 'Content creation, copywriting, blog posts',
    utterances: [
      'write the blog post about the new product feature',
      'create the email newsletter for this month',
      'write the landing page copy for the product launch',
      'create the social media content calendar',
      'write the case study for the enterprise customer',
      'create the product description copy for the e-commerce page',
      'write the press release for the company announcement',
      'create the onboarding email sequence for new users',
      'write the help documentation for the new feature',
      'create the sales deck narrative and talking points',
    ],
  },
  {
    name: 'growth-hacker',
    agentSlug: 'CRO Specialist',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Growth hacking, viral loops, user acquisition experiments',
    utterances: [
      'design the viral referral program for user acquisition',
      'create the growth experiment roadmap for Q3',
      'analyze the conversion funnel and identify improvement opportunities',
      'design the onboarding optimization to improve activation rates',
      'create the product-led growth strategy',
      'analyze cohort retention and design re-engagement campaigns',
      'design the A/B test framework for conversion optimization',
      'identify the viral coefficient and design growth loops',
      'create the growth metrics dashboard and KPI framework',
      'design the freemium to paid conversion optimization strategy',
    ],
  },
];
