/**
 * Codex project configuration generator.
 *
 * Codex reads project configuration from `.codex/config.toml` and project
 * instructions from `AGENTS.md`. This target is additive and selected through
 * the init target flags.
 */

import type { InitOptions } from './types.js';

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function monomindCommand(): { command: string; args: string[] } {
  if (process.platform === 'win32') {
    return { command: 'cmd', args: ['/c', 'npx', '-y', 'monomind@latest', 'mcp', 'start'] };
  }
  return { command: 'npx', args: ['-y', 'monomind@latest', 'mcp', 'start'] };
}

export const CODEX_STATUS_LINE_ITEMS = [
  'model-with-reasoning',
  'project-root',
  'git-branch',
  'context-remaining',
  'task-progress',
  'status',
];

export function generateCodexStatusLineConfig(): string {
  return [
    '[tui]',
    `status_line = [${CODEX_STATUS_LINE_ITEMS.map(tomlString).join(', ')}]`,
    '',
  ].join('\n');
}

/** Generate the project-local adapter used by Codex's native hook runner. */
export function generateCodexHookScript(): string {
  return `// Monomind native Codex hook bridge (generated by monomind init --codex).
const { spawnSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

let input = "";
process.stdin.on("data", (chunk) => { input += chunk; });
process.stdin.on("end", () => {
  let payload = {};
  try { payload = JSON.parse(input || "{}"); } catch (_) { process.exit(0); }
  const cwd = payload.cwd || process.cwd();
  const handler = path.join(cwd, ".claude", "helpers", "hook-handler.cjs");
  if (!fs.existsSync(handler)) process.exit(0);

  const eventName = payload.hook_event_name || "";
  const tool = payload.tool_name || "";
  const toolInput = payload.tool_input || {};
  const shellTools = new Set(["shell_command", "exec_command", "command_execution", "Bash"]);
  const writeTools = new Set(["apply_patch", "edit", "write", "file_edit", "Write", "Edit", "MultiEdit"]);
  let event = null;
  let gateInput = {};
  if (eventName === "PreToolUse" && shellTools.has(tool)) {
    event = "pre-bash";
    gateInput = { command: toolInput.command || toolInput.cmd || toolInput.shell_command || "" };
  } else if (eventName === "PreToolUse" && writeTools.has(tool)) {
    event = "pre-write";
    gateInput = toolInput;
  } else if (eventName === "PostToolUse" && writeTools.has(tool)) {
    event = "post-edit";
    gateInput = toolInput;
  }
  if (!event) process.exit(0);

  let result;
  try {
    result = spawnSync(process.execPath, [handler, event], {
      input: JSON.stringify({ tool_name: tool, tool_input: gateInput, session_id: payload.session_id || "" }),
      encoding: "utf8",
      timeout: 5000,
      cwd,
      env: Object.assign({}, process.env, { CLAUDE_PROJECT_DIR: cwd }),
    });
  } catch (_) { process.exit(0); }
  if (!result || result.status !== 2) process.exit(0);

  let reason = "blocked by Monomind gate";
  for (const line of (result.stderr || "").split("\\n")) {
    try {
      const parsed = JSON.parse(line);
      if (parsed && parsed.decision === "block" && parsed.reason) { reason = parsed.reason; break; }
    } catch (_) {}
  }
  console.error("[monomind] " + reason);
  process.exit(2);
});
`;
}

export function generateCodexHooksConfig(): string {
  const command = 'node .codex/hooks/monomind-hook.cjs';
  const commandWindows = 'node .codex\\\\hooks\\\\monomind-hook.cjs';
  return [
    '# monomind:start native-hooks',
    '[[hooks.PreToolUse]]',
    'matcher = ".*"',
    '[[hooks.PreToolUse.hooks]]',
    'type = "command"',
    `command = ${tomlString(command)}`,
    `command_windows = ${tomlString(commandWindows)}`,
    'statusMessage = "Monomind pre-tool checks"',
    'timeout = 5',
    '',
    '[[hooks.PostToolUse]]',
    'matcher = ".*"',
    '[[hooks.PostToolUse.hooks]]',
    'type = "command"',
    `command = ${tomlString(command)}`,
    `command_windows = ${tomlString(commandWindows)}`,
    'statusMessage = "Monomind post-tool learning"',
    'timeout = 10',
    '# monomind:end native-hooks',
    '',
  ].join('\n');
}

export function generateCodexConfig(options: InitOptions): string {
  const lines = [
    '# Generated by monomind init --codex.',
    '# This project-scoped config is loaded only when the project is trusted.',
    '',
    '[features]',
    'hooks = true',
    '',
    generateCodexStatusLineConfig().trimEnd(),
    '',
  ];

  if (options.mcp.monomind) {
    const server = monomindCommand();
    lines.push(
      '[mcp_servers.monomind]',
      `command = ${tomlString(server.command)}`,
      `args = [${server.args.map(tomlString).join(', ')}]`,
      'enabled = true',
      'startup_timeout_sec = 30',
      'tool_timeout_sec = 120',
      `env = { npm_config_update_notifier = "false", MONOMIND_MODE = "v1", MONOMIND_HOOKS_ENABLED = "true", MONOMIND_TOPOLOGY = ${tomlString(options.runtime.topology)}, MONOMIND_MAX_AGENTS = ${tomlString(String(options.runtime.maxAgents))}, MONOMIND_MEMORY_BACKEND = ${tomlString(options.runtime.memoryBackend)} }`,
      '',
    );
  }

  lines.push(generateCodexHooksConfig().trimEnd(), '');

  return lines.join('\n');
}

export function generateCodexAgentsMd(): string {
  return [
    '# AGENTS.md — Monomind on Codex',
    '',
    'Monomind is wired into Codex through `.codex/config.toml`.',
    'Its MCP tools provide code navigation, impact analysis, persistent memory,',
    'and agent routing for this project.',
    '',
    'Codex currently supports built-in status-line items rather than external',
    'status-line commands. Monomind enables the native footer with model, project,',
    'branch, context, task progress, and run-state indicators.',
    'Native Codex PreToolUse and PostToolUse hooks are enabled for Monomind',
    'security checks and edit outcome learning.',
    '',
    '## Code navigation',
    '',
    'Use Monomind graph tools before broad grep/find exploration when inspecting',
    'the codebase. Fall back to grep when the graph has no relevant results.',
    '',
    '## Memory',
    '',
    'Store durable project insights in Monomind memory and recall prior decisions',
    'before repeating investigation or implementation work.',
    '',
    '## Security',
    '',
    '- Never hardcode secrets or commit `.env` files.',
    '- Validate input at system boundaries.',
    '- Run `npx monomind@latest security scan` after security-related changes.',
    '',
    '## Autonomous organizations',
    '',
    'Org roles can run on Codex with `runtime: "codex"` in their org definition.',
    '',
    '```bash',
    'monomind org run <name> --task "..."',
    '```',
    '',
    '## Project commands',
    '',
    'Use the project commands in `.agents/shared_instructions.md` for build, test,',
    'lint, and typecheck validation.',
    '',
  ].join('\n');
}
