/**
 * Codex project configuration generator.
 *
 * Codex reads project configuration from `.codex/config.toml` and project
 * instructions from `AGENTS.md`. This target is additive and opt-in.
 */

import type { InitOptions } from './types.js';

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function monomindCommand(): { command: string; args: string[] } {
  if (process.platform === 'win32') {
    return { command: 'cmd', args: ['/c', 'npx', '-y', 'monomind@latest', 'mcp', 'start'] };
  }
  return { command: 'npx', args: ['-y', 'monomind@latest', 'mcp', 'start'] };
}

export const CODEX_STATUS_LINE_ITEMS = [
  'model-with-reasoning',
  'project-root',
  'git-branch',
  'context-remaining',
  'task-progress',
  'status',
];

export function generateCodexStatusLineConfig(): string {
  return [
    '[tui]',
    `status_line = [${CODEX_STATUS_LINE_ITEMS.map(tomlString).join(', ')}]`,
    '',
  ].join('\n');
}

export function generateCodexConfig(options: InitOptions): string {
  const lines = [
    '# Generated by monomind init --codex.',
    '# This project-scoped config is loaded only when the project is trusted.',
    '',
    generateCodexStatusLineConfig().trimEnd(),
    '',
  ];

  if (options.mcp.monomind) {
    const server = monomindCommand();
    lines.push(
      '[mcp_servers.monomind]',
      `command = ${tomlString(server.command)}`,
      `args = [${server.args.map(tomlString).join(', ')}]`,
      'enabled = true',
      'startup_timeout_sec = 30',
      'tool_timeout_sec = 120',
      `env = { npm_config_update_notifier = "false", MONOMIND_MODE = "v1", MONOMIND_HOOKS_ENABLED = "true", MONOMIND_TOPOLOGY = ${tomlString(options.runtime.topology)}, MONOMIND_MAX_AGENTS = ${tomlString(String(options.runtime.maxAgents))}, MONOMIND_MEMORY_BACKEND = ${tomlString(options.runtime.memoryBackend)} }`,
      '',
    );
  }

  return lines.join('\n');
}

export function generateCodexAgentsMd(): string {
  return [
    '# AGENTS.md — Monomind on Codex',
    '',
    'Monomind is wired into Codex through `.codex/config.toml`.',
    'Its MCP tools provide code navigation, impact analysis, persistent memory,',
    'and agent routing for this project.',
    '',
    'Codex currently supports built-in status-line items rather than external',
    'status-line commands. Monomind enables the native footer with model, project,',
    'branch, context, task progress, and run-state indicators.',
    '',
    '## Code navigation',
    '',
    'Use Monomind graph tools before broad grep/find exploration when inspecting',
    'the codebase. Fall back to grep when the graph has no relevant results.',
    '',
    '## Memory',
    '',
    'Store durable project insights in Monomind memory and recall prior decisions',
    'before repeating investigation or implementation work.',
    '',
    '## Security',
    '',
    '- Never hardcode secrets or commit `.env` files.',
    '- Validate input at system boundaries.',
    '- Run `npx monomind@latest security scan` after security-related changes.',
    '',
    '## Autonomous organizations',
    '',
    'Org roles can run on Codex with `runtime: "codex"` in their org definition.',
    '',
    '```bash',
    'monomind org run <name> --task "..."',
    '```',
    '',
    '## Project commands',
    '',
    'Use the project commands in `.agents/shared_instructions.md` for build, test,',
    'lint, and typecheck validation.',
    '',
  ].join('\n');
}
