// AUTO-GENERATED by `node scripts/generate-doc-counts.mjs` — do not
// hand-edit. `--check` runs in prepublishOnly (package.json) and blocks
// publish if this drifts from WORKER_CONFIGS.
//
// WORKER_CONFIGS lives in the optional @monoes/hooks package, which may not
// resolve at `init` time. This constant is computed from source at
// doc-generation time instead, so CLAUDE.md/CAPABILITIES.md's worker count
// is always correct without an optional-package import for a doc string.
export const WORKER_COUNT = 9;
