import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { generateClaudeMd } from '../init/claudemd-generator.js';
import { writeSharedInstructions } from '../init/shared-instructions-generator.js';
import { DEFAULT_INIT_OPTIONS, detectPlatform, type InitResult } from '../init/types.js';
import { writeClaudeMd } from '../init/write-claude.js';

// writeSharedInstructions best-effort-seeds memory via a child process; stub
// it out so these tests stay hermetic (same reason as
// write-shared-instructions-force-preserves-content.test.ts). `exec` and
// `execFile` are also required (not called by anything this file exercises)
// since i-035 round 2: write-capabilities.ts now imports doctorCommand,
// which transitively pulls in doctor-env-checks.ts and
// services/crash-reporter.ts, both of which wrap a child_process function
// with `promisify` at module load time.
vi.mock('node:child_process', () => ({
  execFileSync: vi.fn(),
  exec: vi.fn(),
  execFile: vi.fn(),
}));

function freshResult(): InitResult {
  return {
    success: true,
    platform: detectPlatform(),
    created: { directories: [], files: [] },
    updated: [],
    skipped: [],
    removed: [],
    errors: [],
    summary: { skillsCount: 0, commandsCount: 0, agentsCount: 0, hooksEnabled: 0 },
  };
}

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

// The shape that broke in GH #276: a CLAUDE.md generated by a pre-delimiter
// monomind (no `<!-- monomind-block:claude-md -->` anywhere), carrying only
// the older `# monomind:start instructions:claude` pair that a *different*
// subsystem (platform-adapters) appended. Deliberately NOT a verbatim copy of
// today's generator output — the section text has drifted, as a real old
// file's would have — so the detection is exercised on drifted content.
const PRE_MARKER_CLAUDE_MD = `# Claude Code Configuration - Monomind

## Behavioral Rules (Always Enforced)

- Do what has been asked; nothing more, nothing less
- OLD RULE THAT NO LONGER SHIPS

## Build & Test

\`\`\`bash
# Build — a shell comment that looks exactly like a level-1 heading
npm run build
\`\`\`

## Security Rules

- NEVER hardcode API keys, secrets, or credentials in source files

## Support

- Documentation: https://github.com/monoes/monomind
# monomind:start instructions:claude
# Monomind

Use the \`monomind\` MCP tools for graph navigation, impact analysis, memory, and organization work.
# monomind:end instructions:claude
`;

describe('init --force on instruction files written by an older version (GH #276)', () => {
  let tmp: string;
  let projectDir: string;
  let claudeMdPath: string;
  let siPath: string;
  let options: typeof DEFAULT_INIT_OPTIONS;

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), 'monomind-init-276-'));
    projectDir = join(tmp, 'project');
    mkdirSync(join(projectDir, '.agents'), { recursive: true });
    claudeMdPath = join(projectDir, 'CLAUDE.md');
    siPath = join(projectDir, '.agents', 'shared_instructions.md');
    writeFileSync(join(projectDir, 'go.mod'), 'module example.com/project\n\ngo 1.22\n');
    options = { ...DEFAULT_INIT_OPTIONS, targetDir: projectDir, force: true };
  });

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  // (1) the exact reported shape
  it('replaces a pre-marker CLAUDE.md body instead of appending a second copy', async () => {
    writeFileSync(claudeMdPath, PRE_MARKER_CLAUDE_MD);

    await writeClaudeMd(projectDir, options, freshResult());
    const after = readFileSync(claudeMdPath, 'utf-8');

    expect(count(after, '# Claude Code Configuration - Monomind')).toBe(1);
    expect(after).not.toContain('OLD RULE THAT NO LONGER SHIPS');
    expect(after).toContain('<!-- monomind-block:claude-md -->');
    expect(after).toContain('<!-- /monomind-block:claude-md -->');
    // The separately-owned instructions:claude block is another subsystem's
    // and must survive verbatim, in place.
    expect(count(after, '# monomind:start instructions:claude')).toBe(1);
    expect(after).toContain('Use the `monomind` MCP tools');
    // Line count is bounded by "one body + the foreign block", not doubled.
    expect(after.split('\n').length).toBeLessThan(
      PRE_MARKER_CLAUDE_MD.split('\n').length + generateClaudeMd(options).split('\n').length,
    );
  });

  // (2) idempotence
  it('is a byte-identical no-op on the second and third --force run', async () => {
    writeFileSync(claudeMdPath, PRE_MARKER_CLAUDE_MD);

    await writeClaudeMd(projectDir, options, freshResult());
    const first = readFileSync(claudeMdPath, 'utf-8');
    await writeClaudeMd(projectDir, options, freshResult());
    const second = readFileSync(claudeMdPath, 'utf-8');
    await writeClaudeMd(projectDir, options, freshResult());
    const third = readFileSync(claudeMdPath, 'utf-8');

    expect(second).toBe(first);
    expect(third).toBe(first);
  });

  // (3) user text on both sides of the managed body
  it('keeps user-authored text before AND after the managed body, in place', async () => {
    const before = '# House rules\n\nRead docs/ARCH.md before touching the scheduler.\n\n';
    const after = '\n# Deployment\n\nDeploys run from the release branch only.\n';
    writeFileSync(claudeMdPath, `${before}${PRE_MARKER_CLAUDE_MD}${after}`);

    await writeClaudeMd(projectDir, options, freshResult());
    const result = readFileSync(claudeMdPath, 'utf-8');

    expect(result.startsWith('# House rules')).toBe(true);
    expect(result).toContain('Read docs/ARCH.md before touching the scheduler.');
    expect(result.trimEnd().endsWith('Deploys run from the release branch only.')).toBe(true);
    expect(count(result, '# Claude Code Configuration - Monomind')).toBe(1);
    // ...and the user text keeps its position relative to the managed block.
    expect(result.indexOf('# House rules')).toBeLessThan(
      result.indexOf('<!-- monomind-block:claude-md -->'),
    );
    expect(result.indexOf('# Deployment')).toBeGreaterThan(
      result.indexOf('<!-- /monomind-block:claude-md -->'),
    );
  });

  // (4) nothing of monomind's in the file yet
  it('adds the block exactly once to a file with no monomind content', async () => {
    const userOnly = '# CLAUDE.md\n\n## Project\n\nA plain Go service.\n';
    writeFileSync(claudeMdPath, userOnly);

    await writeClaudeMd(projectDir, options, freshResult());
    const first = readFileSync(claudeMdPath, 'utf-8');
    await writeClaudeMd(projectDir, options, freshResult());
    const second = readFileSync(claudeMdPath, 'utf-8');

    expect(first).toContain('A plain Go service.');
    expect(count(first, '<!-- monomind-block:claude-md -->')).toBe(1);
    expect(count(first, '# Claude Code Configuration - Monomind')).toBe(1);
    expect(second).toBe(first);
  });

  // heals a file already doubled by the 2.11.1 bug
  it('collapses a file the buggy version already doubled back to one copy', async () => {
    // What 2.11.1 produced: the unmarked legacy body, then a second, marked copy.
    const doubled = `${PRE_MARKER_CLAUDE_MD}\n<!-- monomind-block:claude-md -->\n${generateClaudeMd(
      options,
    ).trimEnd()}\n<!-- /monomind-block:claude-md -->\n`;
    writeFileSync(claudeMdPath, doubled);

    await writeClaudeMd(projectDir, options, freshResult());
    const after = readFileSync(claudeMdPath, 'utf-8');

    expect(count(after, '# Claude Code Configuration - Monomind')).toBe(1);
    expect(count(after, '<!-- monomind-block:claude-md -->')).toBe(1);
    expect(count(after, '# monomind:start instructions:claude')).toBe(1);
  });

  // old delimiter form for the SAME marker migrates to the current one
  it('migrates a `monomind:start claude-md` pair to the current delimiter form', async () => {
    const oldForm = `# House rules

Keep this.

# monomind:start claude-md
# Claude Code Configuration - Monomind

## Behavioral Rules (Always Enforced)

- OLD RULE THAT NO LONGER SHIPS
# monomind:end claude-md
`;
    writeFileSync(claudeMdPath, oldForm);

    await writeClaudeMd(projectDir, options, freshResult());
    const after = readFileSync(claudeMdPath, 'utf-8');

    expect(after).toContain('<!-- monomind-block:claude-md -->');
    expect(after).not.toContain('monomind:start claude-md');
    expect(after).not.toContain('monomind:end claude-md');
    expect(after).not.toContain('OLD RULE THAT NO LONGER SHIPS');
    expect(count(after, '# Claude Code Configuration - Monomind')).toBe(1);
    expect(after).toContain('Keep this.');
  });

  // conservatism guard: never eat text that merely resembles generated content
  it('leaves a hand-authored file that only borrows the title alone', async () => {
    const lookalike = `# Claude Code Configuration - Monomind

## My own notes

We copied the title from monomind but wrote everything below ourselves.

## Another section of ours

Keep this.
`;
    writeFileSync(claudeMdPath, lookalike);

    await writeClaudeMd(projectDir, options, freshResult());
    const after = readFileSync(claudeMdPath, 'utf-8');

    expect(after).toContain(
      'We copied the title from monomind but wrote everything below ourselves.',
    );
    expect(after).toContain('## Another section of ours');
    expect(after.startsWith(lookalike.trimEnd())).toBe(true);
  });

  // (5) the same writer backs .agents/shared_instructions.md
  it('replaces a pre-marker shared_instructions.md body instead of appending', () => {
    // Title matches what the generator produces for this project (basename).
    const preMarker = `# project — Shared Agent Instructions

> Auto-generated by \`monomind init\`. Edit freely.

## Project Overview

- **Language:** Go

## How to Run

\`\`\`bash
go build ./...
\`\`\`

## Critical Constraints

- OLD CONSTRAINT THAT NO LONGER SHIPS

## Agent Collaboration Rules

- Coordinate through memory.
`;
    writeFileSync(siPath, `${preMarker}\n# Team notes\n\nAsk #platform before schema changes.\n`);

    writeSharedInstructions(projectDir, true, freshResult());
    const first = readFileSync(siPath, 'utf-8');

    expect(count(first, '— Shared Agent Instructions')).toBe(1);
    expect(first).not.toContain('OLD CONSTRAINT THAT NO LONGER SHIPS');
    expect(count(first, '<!-- monomind-block:shared-instructions -->')).toBe(1);
    expect(first).toContain('Ask #platform before schema changes.');

    writeSharedInstructions(projectDir, true, freshResult());
    expect(readFileSync(siPath, 'utf-8')).toBe(first);
  });
});
