import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { writeSharedInstructions } from '../init/shared-instructions-generator.js';
import { detectPlatform, type InitResult } from '../init/types.js';

// writeSharedInstructions best-effort-seeds memory via `npx monomind@latest
// memory store ...` (execFileSync, stdio ignored, failures swallowed). Stub
// it out so these tests stay hermetic and fast — no real subprocess/network
// call, and no behavior under test depends on it. vitest hoists vi.mock
// above the imports above regardless of source order.
vi.mock('node:child_process', () => ({ execFileSync: vi.fn() }));

function freshResult(): InitResult {
  return {
    success: true,
    platform: detectPlatform(),
    created: { directories: [], files: [] },
    updated: [],
    skipped: [],
    errors: [],
    summary: { skillsCount: 0, commandsCount: 0, agentsCount: 0, hooksEnabled: 0 },
  };
}

// Mirrors the before-state from GH #241: hand-edited shared_instructions.md
// with a rewritten header, an added bullet, and a caveat annotation.
const HAND_EDITED = `# mono-agent — Shared Agent Instructions

> Prepended to every agent prompt in this repo. Stack: **Go**.

## Project Overview

- **Repo:** \`github.com/monoes/mono-agent\` — local-first workflow automation engine (n8n alternative), single Go binary \`monoagentcli\`
- **Language:** Go (no npm — any \`npm install\` instructions are stale; ignore them)

## Go Best Practices
- Errors are values — always handle them, never \`_\` a returned error in production
`;

describe('writeSharedInstructions --force preserves hand-authored content (GH #241)', () => {
  let tmp: string;
  let projectDir: string;
  let siPath: string;

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), 'monomind-write-shared-instructions-'));
    projectDir = join(tmp, 'project');
    mkdirSync(join(projectDir, '.agents'), { recursive: true });
    siPath = join(projectDir, '.agents', 'shared_instructions.md');
    // go.mod so detectProjectProfile resolves language: 'go' independent of
    // the stack-detection fix, which is covered separately.
    writeFileSync(join(projectDir, 'go.mod'), 'module example.com/mono-agent\n\ngo 1.22\n');
  });

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it('preserves hand-edited content on --force instead of discarding it', () => {
    writeFileSync(siPath, HAND_EDITED);

    writeSharedInstructions(projectDir, true, freshResult());

    const after = readFileSync(siPath, 'utf-8');
    expect(after).toContain('local-first workflow automation engine (n8n alternative)');
    expect(after).toContain('no npm — any `npm install` instructions are stale');
    expect(after).toContain('Errors are values — always handle them');
  });

  it("still appends monomind's freshly generated content, confined to its own block", () => {
    writeFileSync(siPath, HAND_EDITED);

    writeSharedInstructions(projectDir, true, freshResult());

    const after = readFileSync(siPath, 'utf-8');
    expect(after).toContain('<!-- monomind-block:shared-instructions -->');
    expect(after).toContain('<!-- /monomind-block:shared-instructions -->');
    expect(after).toContain('Auto-generated by `monomind init`');
  });

  it('refreshes the managed block in place on a second --force, without duplicating hand-authored content', () => {
    writeFileSync(siPath, HAND_EDITED);
    writeSharedInstructions(projectDir, true, freshResult());
    const afterFirst = readFileSync(siPath, 'utf-8');

    writeSharedInstructions(projectDir, true, freshResult());
    const afterSecond = readFileSync(siPath, 'utf-8');

    const handAuthoredOccurrences =
      afterSecond.split('local-first workflow automation engine').length - 1;
    expect(handAuthoredOccurrences).toBe(1);
    const generatedOccurrences = afterSecond.split('Auto-generated by `monomind init`').length - 1;
    expect(generatedOccurrences).toBe(1);
    expect(afterSecond).toBe(afterFirst);
  });

  it('does not touch the file at all without force when it already exists (regression guard)', () => {
    writeFileSync(siPath, HAND_EDITED);

    writeSharedInstructions(projectDir, false, freshResult());

    expect(readFileSync(siPath, 'utf-8')).toBe(HAND_EDITED);
  });

  it('writes a fresh file wrapped in the managed block when none exists yet', () => {
    writeSharedInstructions(projectDir, false, freshResult());

    const content = readFileSync(siPath, 'utf-8');
    expect(content).toContain('<!-- monomind-block:shared-instructions -->');
    expect(content).toContain('<!-- /monomind-block:shared-instructions -->');
    expect(content).toContain('**Language:** Go');
  });
});
